import Foundation
import Testing
@testable import Piru

/// Exports the **resolved** substance record — exactly what the detail view
/// renders — to a human/LLM-readable Markdown file, for offline data audits.
///
/// "1:1 with the views" means this calls the *same* resolution surface the
/// detail view does: ``SubstanceLibrary/lookup(_:)`` for the heavy `Substance`,
/// ``MechanismOfActionDatabase/resolvedMechanism(dbMechanism:substanceName:category:)``
/// for the composed mechanism (mirrors `SubstanceDetailView.composedMechanism`),
/// and `SubstanceStore.shared.bindings/pharmacokinetics/metabolism(forSubstanceName:)`
/// for the Receptor-Literature + Pharmacokinetics disclosures. No data is
/// re-derived here — it's the live app pipeline, serialized.
///
/// Opt-in: set `PIRU_AUDIT_EXPORT=1` in the test environment to run. Writes to
/// `<repo>/Audits/` (the test resolves the repo root from `#filePath`). Run:
/// ```
/// xcodebuild test -scheme Piru \
///   -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max,OS=26.4' \
///   -only-testing:PiruTests/SubstanceAuditExportTests
/// ```
/// (with the scheme's TEST env carrying `PIRU_AUDIT_EXPORT=1`), or invoke the
/// `Run audit export` helper which sets it inline.
@Suite("Substance audit export")
struct SubstanceAuditExportTests {
    /// The Library "Common" card allowlist — the popular substances to audit
    /// hard. Mirrors `COMMON_CARD_ALLOWLIST` in `pipeline/build/sqlite.py`, but
    /// resolved through the live store so what's exported is what ships.
    static let commonNames = [
        "Caffeine", "Alcohol", "Nicotine", "Cannabis",
        "Cocaine", "Heroin", "MDMA", "LSD", "Mushrooms",
        "Methamphetamine", "Ketamine", "Amphetamine",
        "Morphine", "Codeine", "Oxycodone",
        "Diazepam", "Alprazolam", "Methylphenidate",
        "Nitrous", "Melatonin",
    ]

    @Test
    @MainActor
    func `Export common-group audit markdown`() throws {
        try runExport(forNames: SubstanceAuditExportTests.commonNames, fileName: "substance-audit-common.md", title: "Common Substances — Data Audit")
    }

    /// The deliberately **enriched** pharmacology set — the flagship seed + RC-expansion groups
    /// (cathinones, pyrrolidinophenones, fluoroamphetamines, tramadol/O-DSMT, gabapentinoids, eugeroics,
    /// benzofurans) read straight from `data/curated/pharmacology-flagship.json`, unioned with the
    /// Common-20. Scoping to the flagship roster (rather than "any substance with a stray upstream Kᵢ /
    /// PK row") keeps the audit to the ~50 substances that actually got the expanded receptor / monoamine
    /// / PK / metabolism treatment — the ones with the tricky issues.
    @MainActor
    static func enrichedNames() -> [String] {
        var names = Set(commonNames)
        names.formUnion(flagshipNames())
        // Resolve each through the store so we audit names the DB actually carries (and de-dup by canon).
        let resolved = names.compactMap { SubstanceLibrary.lookupByNameOrAlias($0)?.name }
        return Set(resolved).sorted { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }
    }

    /// The `name` of every entry in the curated flagship seed. Read from the repo's curated JSON (the
    /// same source the pipeline ingests) via the `#filePath`-resolved repo root.
    static func flagshipNames() -> [String] {
        let url = repoRoot()
            .appendingPathComponent("data/curated/pharmacology-flagship.json")
        guard let data = try? Data(contentsOf: url),
              let arr = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]] else { return [] }
        return arr.compactMap { $0["name"] as? String }
    }

    @Test
    @MainActor
    func `Export enriched-pharmacology audit markdown`() throws {
        try runExport(forNames: Self.enrichedNames(), fileName: "substance-audit-enriched.md", title: "Enriched Pharmacology — Data Audit")
    }

    @Test(.enabled(if: ProcessInfo.processInfo.environment["PIRU_AUDIT_EXPORT_ALL"] != nil))
    @MainActor
    func `Export full-catalog audit markdown`() throws {
        let names = SubstanceStore.shared.all
            .map(\.name)
            .sorted { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }
        try runExport(forNames: names, fileName: "substance-audit-all.md", title: "Full Catalog — Data Audit")
    }

    // MARK: - Driver

    @MainActor
    private func runExport(forNames names: [String], fileName: String, title: String) throws {
        var out = "# \(title)\n\n"
        out += "_Resolved through the live app pipeline (`SubstanceLibrary.lookup` + mechanism/literature/PK resolvers) — 1:1 with the detail view. Generated by `SubstanceAuditExportTests`._\n\n"
        out += "Substances: \(names.count)\n\n---\n\n"

        var missing: [String] = []
        for name in names {
            guard let substance = SubstanceLibrary.lookupByNameOrAlias(name) else {
                missing.append(name)
                continue
            }
            out += AuditSerializer.markdown(for: substance)
            out += "\n---\n\n"
        }
        if !missing.isEmpty {
            out += "## Unresolved names\n\n" + missing.map { "- \($0)" }.joined(separator: "\n") + "\n"
        }

        let dir = Self.repoRoot().appendingPathComponent("Audits", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent(fileName)
        try out.write(to: url, atomically: true, encoding: .utf8)
        print("AUDIT EXPORT → \(url.path) (\(out.count) chars, \(names.count - missing.count) resolved, \(missing.count) missing)")
        #expect(missing.isEmpty, "Some audited names did not resolve: \(missing)")
    }

    /// `<repo>/PiruTests/SubstanceAuditExportTests.swift` → `<repo>`.
    private static func repoRoot(file: StaticString = #filePath) -> URL {
        URL(fileURLWithPath: "\(file)")
            .deletingLastPathComponent() // PiruTests/
            .deletingLastPathComponent() // repo root
    }
}

// MARK: - Serializer

/// Pure Markdown serializer for a resolved ``Substance`` plus its
/// store-resolved literature/PK rows. Kept separate from the test so the
/// formatting is one obvious place to extend.
@MainActor
enum AuditSerializer {
    static func markdown(for s: Substance) -> String {
        var m = "## \(s.displayTitle)\n\n"

        // Identity
        var idLines: [String] = []
        if s.name != s.displayTitle { idLines.append("- **Canonical name:** \(s.name)") }
        idLines.append("- **Category:** \(s.category.rawValue)")
        idLines.append("- **Display class:** \(s.displayClass.rawValue)")
        if let reg = s.regulatoryStatus { idLines.append("- **Regulatory status:** \(reg)") }
        if !s.displayAliases.isEmpty { idLines.append("- **Aliases:** \(s.displayAliases.joined(separator: ", "))") }
        if !s.tags.isEmpty { idLines.append("- **Tags:** \(s.tags.joined(separator: ", "))") }
        if s.isStub { idLines.append("- **Limited data (stub)**") }
        m += idLines.joined(separator: "\n") + "\n\n"

        // Chemistry + physicochemical
        m += chemistrySection(s)

        // Doses & durations per route
        m += routesSection(s)

        if let hl = s.halfLifeMinutes {
            m += "**Half-life:** \(fmt(hl)) min (\(fmt(hl / 60)) h)\n\n"
        }

        // Mechanism (composed — same call the detail view's `composedMechanism` makes)
        if let moa = MechanismOfActionDatabase.resolvedMechanism(
            dbMechanism: s.mechanismOfAction, substanceName: s.name, category: s.category,
        ) {
            m += mechanismSection(moa)
        }

        // Computed monoamine profile + receptor literature (Ki/EC50) — both read the same bindings.
        let lit = SubstanceStore.shared.bindings(forSubstanceName: s.name)
        if !lit.isEmpty {
            m += monoamineProfileSection(lit, name: s.name)
            m += receptorLiteratureSection(lit)
        }

        // Pharmacokinetics + metabolism
        let pk = SubstanceStore.shared.pharmacokinetics(forSubstanceName: s.name)
        let metab = SubstanceStore.shared.metabolism(forSubstanceName: s.name)
        if !pk.isEmpty || !metab.isEmpty { m += pharmacokineticsSection(pk: pk, metab: metab) }

        // Effects
        if !s.effects.isEmpty {
            m += "### Effects\n\n" + s.effects.map { "- \($0)" }.joined(separator: "\n") + "\n\n"
        }
        if !s.subjectiveEffects.isEmpty {
            m += "### Subjective effects\n\n"
            for e in s.subjectiveEffects {
                m += "- **\(e.name)** — \(e.description)\n"
            }
            m += "\n"
        }

        // Tolerance
        if let t = s.toleranceInfo {
            m += "**Tolerance:** build \(t.buildRate); halves in \(fmt(t.halfLife)) d; full reset \(fmt(t.fullResetDays)) d\n\n"
        }

        // Benzo equivalency
        if let d = s.diazepamEquivalent {
            var parts: [String] = []
            if let dose = d.doseMg { parts.append("\(fmt(dose)) mg") }
            if let eq = d.equivalentDiazepamMg { parts.append("≈ \(fmt(eq)) mg diazepam") }
            if let txt = d.displayText { parts.append(txt) }
            if !parts.isEmpty { m += "**Diazepam equivalent:** \(parts.joined(separator: " · "))\n\n" }
        }

        // Clinical
        if !s.indications.isEmpty {
            m += "### Medical uses\n\n" + s.indications.map { "- \($0)" }.joined(separator: "\n") + "\n\n"
        }
        if !s.contraindications.isEmpty {
            m += "### Contraindications & warnings\n\n"
            for c in s.contraindications {
                m += "- \(c.isBoxedWarning ? "**[BOXED]** " : "")\(c.text)\n"
            }
            m += "\n"
        }

        // Overview prose
        if let o = s.overview, !o.text.isEmpty {
            m += "### Overview\(o.machineTranslated ? " _(machine-translated)_" : "")\n\n\(o.text)\n\n"
        }

        // References
        if !s.references.isEmpty {
            m += "### References\n\n"
            for r in s.references {
                var bits: [String] = [r.label]
                if let doi = r.doi, !doi.isEmpty { bits.append("doi:\(doi)") }
                if let pmid = r.pmid { bits.append("PMID:\(pmid)") }
                if let url = r.url, url.hasPrefix("http") { bits.append(url) }
                m += "- \(bits.joined(separator: " · "))\n"
            }
            m += "\n"
        }

        return m
    }

    // MARK: Sections

    private static func chemistrySection(_ s: Substance) -> String {
        var lines: [String] = []
        if let f = s.formula { lines.append("- **Formula:** \(f)") }
        if let mw = s.molarMass { lines.append("- **Molar mass:** \(fmt(mw)) g/mol") }
        if let cas = s.cas { lines.append("- **CAS:** \(cas)") }
        if let ik = s.inchikey { lines.append("- **InChIKey:** `\(ik)`") }
        if let cid = s.pubchemCID { lines.append("- **PubChem CID:** \(cid)") }
        if let iupac = s.iupacName { lines.append("- **IUPAC:** \(iupac)") }
        if let smiles = s.smiles { lines.append("- **SMILES:** `\(smiles)`") }
        if let p = s.physicochemical {
            if let v = p.logP { lines.append("- **LogP:** \(fmt(v))") }
            if let v = p.logD { lines.append("- **LogD:** \(fmt(v))") }
            if let v = p.pKa { lines.append("- **pKa:** \(fmt(v))") }
            if let v = p.tpsa { lines.append("- **TPSA:** \(fmt(v)) Å²") }
            if let v = p.hba { lines.append("- **H-bond acceptors:** \(v)") }
            if let v = p.hbd { lines.append("- **H-bond donors:** \(v)") }
            if let v = p.meltingPointC { lines.append("- **Melting point:** \(fmt(v)) °C") }
            if let v = p.boilingPointC { lines.append("- **Boiling point:** \(fmt(v)) °C") }
            if let v = p.ld50OralMgPerKg { lines.append("- **LD50 (oral, rodent):** \(fmt(v)) mg/kg") }
            if let v = p.ld50DermalMgPerKg { lines.append("- **LD50 (dermal, rodent):** \(fmt(v)) mg/kg") }
        }
        guard !lines.isEmpty else { return "" }
        return "### Chemistry\n\n" + lines.joined(separator: "\n") + "\n\n"
    }

    private static func routesSection(_ s: Substance) -> String {
        guard !s.routes.isEmpty else { return "" }
        var m = "### Doses & durations\n\n"
        for r in s.routes {
            m += "**\(String(localized: r.route.localizedName))** (\(r.unit))\n\n"
            let d = r.doses
            var ladder: [String] = []
            if let v = d.threshold { ladder.append("threshold \(fmt(v))") }
            if let v = d.light { ladder.append("light \(fmt(v.lowerBound))–\(fmt(v.upperBound))") }
            if let v = d.common { ladder.append("common \(fmt(v.lowerBound))–\(fmt(v.upperBound))") }
            if let v = d.strong { ladder.append("strong \(fmt(v.lowerBound))–\(fmt(v.upperBound))") }
            if let v = d.heavy { ladder.append("heavy \(fmt(v))+") }
            if !ladder.isEmpty { m += "- Dose: \(ladder.joined(separator: ", ")) \(r.unit)\n" }
            if let dur = r.duration {
                var phases: [String] = []
                func add(_ label: String, _ p: DurationRange?) {
                    if let p { phases.append("\(label) \(p.displayString)") }
                }
                add("onset", dur.onset); add("comeup", dur.comeup); add("peak", dur.peak)
                add("offset", dur.offset); add("after", dur.afterglow); add("total", dur.total)
                if !phases.isEmpty { m += "- Duration: \(phases.joined(separator: " · "))\n" }
            }
            m += "\n"
        }
        return m
    }

    private static func mechanismSection(_ moa: MechanismOfAction) -> String {
        var m = "### Mechanism of action\n\n\(moa.summary)\n\n"
        if !moa.description.isEmpty, moa.description != moa.summary {
            m += "\(moa.description)\n\n"
        }
        if !moa.primaryTargets.isEmpty {
            m += "**Primary targets:** \(moa.primaryTargets.joined(separator: " · "))\n\n"
        }
        if !moa.bindings.isEmpty {
            m += "| Target | Action | Affinity |\n|---|---|---|\n"
            for b in moa.bindings {
                m += "| \(b.target) | \(String(localized: b.action.displayName)) | \(affinityName(b.affinity)) |\n"
            }
            m += "\n"
        }
        return m
    }

    /// The 10 µM relevance cutoff — a Kᵢ at/above this is "no meaningful affinity" by the standard
    /// receptor-pharmacology convention. Applied to **Kᵢ only** (off-target binding noise like ketamine's
    /// σ / µ-opioid); functional EC₅₀/IC₅₀ transporter rows are never capped (a releaser's DAT EC₅₀ is
    /// legitimately tens of µM yet is the primary mechanism). The audit flags what the cap would hide.
    static let kiCapNanomolar: Double = 10_000

    private static func receptorLiteratureSection(_ hits: [SubstanceStore.BindingHit]) -> String {
        var m = "### Receptor literature (Ki/EC50)\n\n| Target | Action | Ki (nM) | EC50 (nM) | IC50 (nM) | Species | Source | Ref | 10µM cap |\n|---|---|---|---|---|---|---|---|---|\n"
        for h in hits {
            let ref = h.pmid.map { "PMID:\($0)" } ?? (h.doi.map { "doi:\($0)" } ?? "")
            let capped = (h.kiNm.map { $0 >= kiCapNanomolar } ?? false) ? "HIDE" : ""
            m += "| \(h.target) | \(h.action) | \(h.kiNm.map(fmt) ?? "") | \(h.ec50Nm.map(fmt) ?? "") | \(h.ic50Nm.map(fmt) ?? "") | \(h.species ?? "") | \(h.sourceSlug) | \(ref) | \(capped) |\n"
        }
        return m + "\n"
    }

    /// The computed ``MonoamineProfile`` — exactly what the detail view's Monoamine Profile card derives
    /// from these same binding rows (mechanism, DAT:SERT lean, 5-HT2B / mis-sold flags). Surfacing it in
    /// the audit makes the card's classification reviewable without a screenshot.
    private static func monoamineProfileSection(_ hits: [SubstanceStore.BindingHit], name: String) -> String {
        guard let p = MonoamineProfile.from(bindings: hits, substanceName: name) else { return "" }
        var m = "### Monoamine profile (computed card)\n\n"
        m += "- **Mechanism:** \(String(localized: p.mechanismLabel))\n"
        if let r = p.datSertRatio {
            m += "- **DAT:SERT ratio:** \(fmt(r)) → \(String(localized: p.leanLabel))\n"
        } else {
            m += "- **DAT:SERT ratio:** — (DAT or SERT data missing)\n"
        }
        if let pos = p.leanPosition { m += "- **Spectrum marker (0 = serotonin … 1 = dopamine):** \(String(format: "%.2f", pos))\n" }
        if p.engages5HT2B { m += "- **5-HT2B agonist flag:** YES (shows valvulopathy callout)\n" }
        if p.misSoldAsMDMA { m += "- **Mis-sold-as-MDMA flag:** YES\n" }
        return m + "\n"
    }

    private static func pharmacokineticsSection(pk: [SubstanceStore.PKRouteHit], metab: [SubstanceStore.MetabolismHit]) -> String {
        var m = "### Pharmacokinetics\n\n"
        if !pk.isEmpty {
            m += "| Route | F% | Tmax(min) | t½(min) | Vd(L/kg) | CL | PPB% | Cmax(ng/mL) | Source | Ref |\n|---|---|---|---|---|---|---|---|---|---|\n"
            for p in pk {
                let ref = p.pmid.map { "PMID:\($0)" } ?? (p.doi.map { "doi:\($0)" } ?? "")
                m += "| \(p.route) | \(p.bioavailabilityPct.map(fmt) ?? "") | \(p.tmaxMin.map(fmt) ?? "") | \(p.halfLifeMin.map(fmt) ?? "") | \(p.vdLPerKg.map(fmt) ?? "") | \(p.clearanceMlPerMinPerKg.map(fmt) ?? "") | \(p.proteinBindingPct.map(fmt) ?? "") | \(p.cmaxNgPerMl.map(fmt) ?? "") | \(p.sourceSlug) | \(ref) |\n"
            }
            m += "\n"
        }
        if !metab.isEmpty {
            m += "**Metabolism**\n\n| Enzyme | Clearance% | Metabolite | Active | Source | Ref |\n|---|---|---|---|---|---|\n"
            for x in metab {
                let ref = x.pmid.map { "PMID:\($0)" } ?? (x.doi.map { "doi:\($0)" } ?? "")
                let active = x.metaboliteActive.map { $0 ? "active" : "inactive" } ?? ""
                m += "| \(x.enzyme) | \(x.fractionOfClearancePct.map(fmt) ?? "") | \(x.metaboliteName ?? "") | \(active) | \(x.sourceSlug) | \(ref) |\n"
            }
            m += "\n"
        }
        return m
    }

    // MARK: Helpers

    private static func affinityName(_ a: BindingAffinity) -> String {
        switch a {
        case .weak: "weak (1)"
        case .significant: "significant (2)"
        case .primary: "primary (3)"
        }
    }

    private static func fmt(_ v: Double) -> String {
        v == v.rounded() ? String(format: "%.0f", v) : String(format: "%g", v)
    }
}
