import Foundation
import Testing
@testable import Piru

/// Exports **exactly what the Tolerance tool screen shows** for a seeded poly-drug dose log, to a
/// human/LLM-readable Markdown file — the tolerance-axis sibling of ``SubstanceAuditExportTests``.
///
/// "1:1 with the screen" means it drives the *same* engine the tool does
/// (``ToleranceStore/simulate(doses:params:now:weightKg:timestepMinutes:lookbackDays:)`` over
/// store-resolved ``PharmacologyParameters``, **one ``ClassTolerance`` per mechanism class**) and
/// reproduces ``ToleranceToolView``'s grouping and per-card facets. Numbers are not re-derived.
///
/// It also dumps the two things the screen folds away, where data-quality bugs live:
/// 1. **Silently dropped substances** — logged drugs the engine can't model
///    (``PharmacologyParameters/canComputeOccupancy`` false), with the missing input — the tool now
///    surfaces these in its "Can't predict yet" section instead of implying rested.
/// 2. **Raw target strings** per substance — the un-canonicalised `bindings.target` values, each
///    annotated with the **action-aware class** it now routes to (so off-mechanism engagements that
///    drop out — a 5-HT2A antagonist, an α7 antagonist — are visible as `unknown`).
///
/// Opt-in: set `PIRU_AUDIT_EXPORT=1` (`TEST_RUNNER_PIRU_AUDIT_EXPORT=1` under xcodebuild). Run:
/// ```
/// TEST_RUNNER_PIRU_AUDIT_EXPORT=1 xcodebuild test -scheme Piru \
///   -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max,OS=26.4' \
///   -only-testing:PiruTests/ToleranceAuditExportTests
/// ```
@Suite("Tolerance audit export")
struct ToleranceAuditExportTests {
    private struct Plan {
        let name: String
        let doseMg: Double
        let everyDays: Double
        let spanDays: Double
    }

    /// A deliberately messy, heavy, recent poly-drug log chosen to surface every reported problem:
    /// off-target noise (mirtazapine H1), enantiomer/expression duplicates (tramadol, pregabalin,
    /// memantine), wrong-direction classes (antagonists modelled as agonist desensitisation), spurious
    /// stimulant/releaser cards (tramadol's weak NET/SERT), and the silent opioid drop (kratom).
    private static let regimen: [Plan] = [
        Plan(name: "Mirtazapine", doseMg: 30, everyDays: 1, spanDays: 21),
        Plan(name: "Amphetamine", doseMg: 30, everyDays: 1, spanDays: 30),
        Plan(name: "Methamphetamine", doseMg: 40, everyDays: 3, spanDays: 30),
        Plan(name: "Cocaine", doseMg: 80, everyDays: 4, spanDays: 28),
        Plan(name: "DMT", doseMg: 40, everyDays: 6, spanDays: 30),
        Plan(name: "MDMA", doseMg: 120, everyDays: 7, spanDays: 42),
        Plan(name: "Ketamine", doseMg: 80, everyDays: 2, spanDays: 24),
        Plan(name: "Memantine", doseMg: 20, everyDays: 1, spanDays: 30),
        Plan(name: "Dextromethorphan", doseMg: 200, everyDays: 7, spanDays: 35),
        Plan(name: "Pregabalin", doseMg: 300, everyDays: 1, spanDays: 21),
        Plan(name: "Tramadol", doseMg: 100, everyDays: 1, spanDays: 21),
        Plan(name: "Kratom", doseMg: 5_000, everyDays: 1, spanDays: 30),
        Plan(name: "Mitragynine", doseMg: 50, everyDays: 1, spanDays: 20),
        Plan(name: "Oxycodone", doseMg: 20, everyDays: 3, spanDays: 21),
        Plan(name: "Diazepam", doseMg: 10, everyDays: 1, spanDays: 21),
        Plan(name: "Caffeine", doseMg: 200, everyDays: 1, spanDays: 30),
        Plan(name: "Nicotine", doseMg: 8, everyDays: 0.25, spanDays: 30),
        Plan(name: "Cannabis", doseMg: 15, everyDays: 1, spanDays: 30),
        Plan(name: "LSD", doseMg: 0.1, everyDays: 10, spanDays: 30),
        Plan(name: "Mushrooms", doseMg: 2_500, everyDays: 12, spanDays: 30),
    ]

    @Test(.enabled(if: ProcessInfo.processInfo.environment["PIRU_AUDIT_EXPORT"] != nil))
    @MainActor
    func `Export tolerance-screen audit markdown`() throws {
        let now = Date.now
        let doses = Self.buildDoses(now: now)

        let uniqueNames = Array(Set(doses.map(\.substance)))
        var params: [String: PharmacologyParameters] = [:]
        for name in uniqueNames {
            params[name] = SubstanceStore.shared.pharmacologyParameters(forSubstanceName: name)
        }

        let states = ToleranceStore.simulate(doses: doses, params: params, now: now, weightKg: 75)

        var out = "# Tolerance Tool — Screen Audit\n\n"
        out += "_Live replay of a seeded poly-drug log through `ToleranceStore.simulate`, rendered 1:1 with `ToleranceToolView` (one card per mechanism class). Generated by `ToleranceAuditExportTests`. Body weight 75 kg._\n\n"
        out += "Logged substances: \(uniqueNames.count). Mechanism cards: \(states.count).\n\n---\n\n"

        out += Self.visibleCardsSection(states: states)
        out += Self.droppedSubstancesSection(uniqueNames: uniqueNames, params: params)
        out += Self.rawTargetsSection(uniqueNames: uniqueNames, params: params)

        let dir = Self.repoRoot().appendingPathComponent("Audits", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("tolerance-screen-audit.md")
        try out.write(to: url, atomically: true, encoding: .utf8)
        print("TOLERANCE AUDIT EXPORT → \(url.path) (\(out.count) chars, \(states.count) cards)")
    }

    // MARK: - Seed

    private static func buildDoses(now: Date) -> [ToleranceStore.SimDose] {
        var doses: [ToleranceStore.SimDose] = []
        for plan in regimen {
            var back = 0.0
            while back <= plan.spanDays {
                let ts = now.addingTimeInterval(-back * 86_400)
                doses.append(.init(substance: plan.name, amountMg: plan.doseMg, timestamp: ts))
                back += plan.everyDays
            }
        }
        return doses
    }

    // MARK: - Visible cards (mirrors ToleranceToolView grouping + facets)

    private struct Row {
        let snapshot: ClassTolerance
        let params: ReceptorClasses.Parameters
        var isSafetyCritical: Bool {
            switch params.safetyAxis {
            case .resetOverdose, .dependenceKindling: true
            default: false
            }
        }
    }

    private static func visibleCardsSection(states: [ReceptorClasses.ReceptorClass: ClassTolerance]) -> String {
        let rows: [Row] = states.values.compactMap { snap in
            let p = ReceptorClasses.parameters(for: snap.receptorClass)
            guard snap.severity > 0.03 else { return nil }
            return Row(snapshot: snap, params: p)
        }
        .sorted { $0.snapshot.severity > $1.snapshot.severity }

        let attention = rows.filter(\.isSafetyCritical)
        let active = rows.filter { !$0.isSafetyCritical }

        var m = "## Cards shown on screen\n\n\(rows.count) mechanism cards.\n\n"
        m += "### ⚠ Needs attention\n\n"
        m += attention.isEmpty ? "_none_\n\n" : attention.map(cardMarkdown).joined()
        m += "### Active tolerance\n\n"
        m += active.isEmpty ? "_none_\n\n" : active.map(cardMarkdown).joined()
        return m + "---\n\n"
    }

    private static func cardMarkdown(_ row: Row) -> String {
        let s = row.snapshot
        var m = "#### \(loc(s.receptorClass.displayName)) — **\(loc(stateWord(s.severity)))**\n\n"
        m += "- **class:** `\(s.receptorClass.rawValue)`\n"
        if !s.subTargets.isEmpty { m += "- **sub-targets:** \(s.subTargets.joined(separator: ", "))\n" }
        if !s.contributors.isEmpty { m += "- **driven by:** \(s.contributors.joined(separator: ", "))\n" }
        m += "- **shift S:** \(String(format: "%.2f", s.shiftFactor))× · **sAcute/sAdaptive/sDeep:** \(fmt3(s.sAcute)) / \(fmt3(s.sAdaptive)) / \(fmt3(s.sDeep))\n"
        m += "- **rep. occupancy:** \(pct(s.representativeOccupancy))% · **response:** \(pct(s.responseFraction))% of rested\n"
        m += "- **severity:** \(String(format: "%.3f", s.severity)) · **confidence:** \(loc(s.confidence.label))\n"
        m += "- **facets:** sensitivity ~\(pct(s.responseFraction))% of rested · if you stop now → \(recoveryValue(row))\n"
        if let note = safetyNote(for: row.params.safetyAxis) { m += "- ⚠️ \(loc(note))\n" }
        return m + "\n"
    }

    // MARK: - Hidden: silently dropped substances

    @MainActor
    private static func droppedSubstancesSection(
        uniqueNames: [String], params: [String: PharmacologyParameters],
    ) -> String {
        var m = "## Can't predict yet (incomplete data)\n\n"
        m += "Logged, but `canComputeOccupancy` is false. The tool now surfaces these honestly instead of implying rested.\n\n"
        var any = false
        for name in uniqueNames.sorted() {
            guard let p = params[name], !p.canComputeOccupancy else { continue }
            any = true
            var missing: [String] = []
            if p.molarMassGramsPerMole == nil { missing.append("molar mass") }
            if p.vdLPerKg == nil { missing.append("Vd") }
            if p.bioavailabilityFraction == nil { missing.append("bioavailability (F)") }
            if p.halfLifeMinutes == nil { missing.append("half-life") }
            if p.primaryTarget == nil { missing.append("any target with a Kᵢ/EC₅₀/IC₅₀") }
            m += "- **\(name)** — missing: \(missing.joined(separator: ", "))\n"
        }
        if !any { m += "_None — every logged substance computed._\n" }
        return m + "\n---\n\n"
    }

    // MARK: - Hidden: raw target strings → action-aware class

    @MainActor
    private static func rawTargetsSection(
        uniqueNames: [String], params: [String: PharmacologyParameters],
    ) -> String {
        var m = "## Raw target strings → action-aware class\n\n"
        m += "`unknown` = off-mechanism (dropped). Canonical name in brackets is the de-duplicated label.\n\n"
        for name in uniqueNames.sorted() {
            guard let p = params[name], !p.targets.isEmpty else { continue }
            m += "**\(name)**\n\n"
            for t in p.targets {
                let cls = ReceptorClasses.classify(target: t.target, action: t.action)
                let canon = ReceptorClasses.canonicalTarget(t.target)
                m += "- `\(t.target)` [\(canon)] (\(loc(t.action.displayName)), \(t.kind.rawValue) \(fmt(t.halfMaxNanomolar)) nM) → **\(cls.rawValue)**\n"
            }
            m += "\n"
        }
        return m
    }

    // MARK: - Copy mirrors

    private static func stateWord(_ severity: Double) -> LocalizedStringResource {
        switch severity {
        case ..<0.15: "Rested"
        case ..<0.4: "Mild"
        case ..<0.6: "Moderate"
        case ..<0.85: "Heavy"
        default: "Depleted"
        }
    }

    private static func recoveryValue(_ row: Row) -> String {
        let s = row.snapshot
        let occupancy = min(0.999_999, max(0, s.representativeOccupancy))
        let ratio = occupancy / (1 - occupancy)
        let targetShift = max(1, (ratio + 1) / 0.9 - ratio)
        let layers = [
            (s: s.sAcute, tau: row.params.tauAcuteMinutes),
            (s: s.sAdaptive, tau: row.params.tauAdaptiveMinutes),
            (s: s.sDeep, tau: row.params.tauDeepMinutes),
        ]
        guard let mins = PDModel.shiftDecayMinutes(layers: layers, toShift: targetShift), mins > 0 else { return "nearly rested" }
        return durationPhrase(minutes: mins)
    }

    private static func safetyNote(for axis: ReceptorClasses.SafetyAxis) -> LocalizedStringResource? {
        switch axis {
        case .resetOverdose: "Reset-overdose risk after a break — restart low, keep naloxone accessible."
        case .dependenceKindling: "Dependence + kindling — taper, don't quit cold."
        case .alpha2Rebound: "α₂-agonist discontinuation rebound — taper, don't stop cold (rebound hypertension)."
        case .betaRebound: "β-blocker discontinuation rebound — taper, don't stop cold (rebound tachycardia/hypertension)."
        case .stimulantLoad, .serotonergicLoad, .cumulativeToxicity, .hppd, .none: nil
        }
    }

    private static func durationPhrase(minutes: Double) -> String {
        let hours = minutes / 60, days = hours / 24
        if days >= 60 { return "~\(Int((days / 30).rounded())) months" }
        if days >= 14 { return "~\(Int((days / 7).rounded())) weeks" }
        if days >= 1.5 { return "~\(Int(days.rounded())) days" }
        if hours >= 1 { return "~\(Int(hours.rounded())) hours" }
        return "under an hour"
    }

    private static func pct(_ value: Double) -> Int {
        Int((min(1, max(0, value)) * 100).rounded())
    }
    private static func fmt3(_ value: Double) -> String {
        String(format: "%.3f", value)
    }
    private static func fmt(_ v: Double) -> String {
        v >= 100 ? String(Int(v.rounded())) : String(format: "%.1f", v)
    }
    private static func loc(_ r: LocalizedStringResource) -> String {
        String(localized: r)
    }

    private static func repoRoot(file: StaticString = #filePath) -> URL {
        URL(fileURLWithPath: "\(file)").deletingLastPathComponent().deletingLastPathComponent()
    }
}
