import SwiftUI

/// A skin is a named visual identity for the app: a palette, a surface
/// treatment, a type design, and a decoration scene. It is *not* a light/dark
/// pair — every skin carries both appearances (and high-contrast variants) in
/// the asset catalog, so the system's colour scheme keeps working inside any skin.
///
/// ## Where a skin's colours live
///
/// In `Shared/Assets.xcassets`, under `skin/<id>/…`, generated by
/// `design-system/color/generate_colorsets.py` from `palette-skins.json`
/// exactly like the default tokens. Each skin builds one ``SkinPalette`` from
/// the Xcode-generated symbols for its namespace — never a string lookup, so
/// a missing colorset is a compile error, and `ColorContrastTests` gates every
/// skin against the same floors as the default.
///
/// The default skin reads the un-namespaced tokens (`surface/card`,
/// `text/secondary`, `AccentColor`) — the catalog the app shipped with, untouched.
///
/// ## What a skin never touches
///
/// Graphs. The timeline spine, sparklines and PK charts read `series.color`
/// and `Color.primary` with their own opacities and never see `Theme`, so a
/// skin cannot restyle them. Per-substance identity colours (L3) and the L2
/// encoding scales (routes, dose tiers, phases) are likewise not a skin's to
/// change — only their surrounding chrome is.
///
/// Lives in `Shared/` so the widget and Live Activity targets can resolve the
/// active skin's colours from the same catalog; the store that *chooses* the
/// skin (`SkinStore`) is app-only.
enum Skin: String, CaseIterable, Identifiable, Sendable {
    /// The app's own look: soft pink light, hot pink dark, Liquid Glass.
    case piru
    /// ely.pink — the author's homepage. Night (plum-black, hot pink, lilac,
    /// mint) and pink (cream cards on a pink ground with near-black edges).
    /// Solid edged cards with hard offset shadows; nothing tilts.
    case elyPink
    /// Tsuki — the author's journaling app. Deep purple night, lavender
    /// hairlines, glows instead of shadows, a sleeping moon and drifting stars.
    case tsuki
    /// Starfield — Astrelia's steel-blue sky: edged cards, gold stars, a dense
    /// twinkling field.
    case astrelia
    /// Jellyfish — deep water. Bioluminescent cyan and violet, soft glowing
    /// cards, bubbles rising and jellyfish swimming up behind everything.
    case jellyfish

    var id: String { rawValue }

    /// Picker name. Localized like every user-facing string.
    var displayName: LocalizedStringResource {
        switch self {
        case .piru: "Piru"
        case .elyPink: "ely.pink"
        case .tsuki: "Tsuki"
        case .astrelia: "Starfield"
        case .jellyfish: "Jellyfish"
        }
    }

    /// One line under the name in the picker.
    var tagline: LocalizedStringResource {
        switch self {
        case .piru: "Soft pink, hot pink, liquid glass"
        case .elyPink: "Night and pink, stickers and pixels"
        case .tsuki: "Deep purple night, a sleeping moon"
        case .astrelia: "Steel blue and gold under a thousand stars"
        case .jellyfish: "Deep water, bioluminescence, jellyfish"
        }
    }

    // MARK: - Current

    /// The skin the app is showing, readable from `Shared/` code that cannot
    /// see `SkinStore`. The app installs a provider that reads the observable
    /// store (so reads inside a `body` are tracked); before that, and in the
    /// extensions, it falls back to the persisted choice.
    nonisolated static var current: Skin { currentProvider() }

    /// Replaced once by `SkinStore.activate()` at launch; read on the main
    /// thread from view bodies. `nonisolated(unsafe)` because the members of
    /// this `Sendable` enum are nonisolated and the write happens before any
    /// view exists.
    nonisolated(unsafe) static var currentProvider: @Sendable () -> Skin = { SkinDefaults.storedSkin() }

    // MARK: - Palette

    /// The skin's tokens, from its catalog namespace.
    var palette: SkinPalette {
        switch self {
        case .piru: .piru
        case .elyPink: .elyPink
        case .tsuki: .tsuki
        case .astrelia: .astrelia
        case .jellyfish: .jellyfish
        }
    }

    /// Label colour on an ``accentMark`` fill (buttons, tab stickers). Gated
    /// 4.5:1 against ``accent``. The default skin's white-on-accent is the
    /// system's own choice for `.glassProminent`.
    var onAccent: Color { palette.onAccent }

    /// Brand accent and control tint. **Text-safe** in every skin: the app uses
    /// one token for both copy and marks, so where a skin's vivid mark colour
    /// fails as small text (ely.pink's hot pink on cream, 2.9:1) this is the
    /// darker `accent/text` twin and ``accentMark`` carries the vivid one.
    var accent: Color { palette.accent }

    /// The vivid accent for standalone marks: rings, glows, selection fills
    /// under white text. Gated at the 3:1 non-text floor, never used as copy.
    var accentMark: Color { palette.accentMark }

    /// De-emphasized body text. Gated AA 4.5:1 on `cardBackground`.
    var secondaryLabel: Color { palette.secondaryLabel }

    /// Page backdrop.
    var background: Color { palette.background }

    /// Card / raised surface fill.
    var cardBackground: Color { palette.cardBackground }

    /// Text-field and other input fills.
    var inputBackground: Color { palette.inputBackground }

    /// Eyebrows, section labels, sticker shadows — the skin's "wine". The
    /// default skin has no such role and uses secondary text.
    var eyebrow: Color { palette.eyebrow }

    /// Status colours. Skins may re-seed the L1 ladder; the roles and the
    /// `text` / `accent` split are fixed by the design system.
    func semantic(_ role: SemanticRole, _ variant: SemanticVariant) -> Color {
        palette.semantic(role, variant)
    }

    // MARK: - Decorations

    /// The decoration layer behind every screen. `nil` for skins that keep
    /// the ground plain. Colours come from the skin's own tokens; the app
    /// draws them, so nothing here is content.
    var decorations: SkinDecorations? {
        switch self {
        case .piru:
            nil
        case .elyPink:
            SkinDecorations(
                scene: .stickers,
                glyphs: [
                    SkinGlyph("★", semantic(.caution, .accent)), SkinGlyph("☆", semantic(.caution, .accent)),
                    SkinGlyph("✦", .white), SkinGlyph("✧", .white),
                    SkinGlyph("♡", accentMark), SkinGlyph("♥", accentMark), SkinGlyph("✿", accentMark),
                    SkinGlyph("✚", eyebrow), SkinGlyph("♠", eyebrow), SkinGlyph("✗", eyebrow),
                    SkinGlyph("✦", semantic(.success, .accent)),
                ],
                // The site's `.term::before/::after`: ✧ on the top-right edge, ♡
                // on the bottom-left.
                frameCorners: (SkinGlyph("✧", semantic(.caution, .accent)), SkinGlyph("♡", accentMark)),
                // The site's cursor trail: a ♡ that floats up from every tap.
                tapGlyph: SkinGlyph("♡", accentMark),
            )
        case .tsuki:
            // Tsuki's `DreamyEffects`: a sparse field of haloed stars over two
            // nebula glows, and its sleeping moon.
            SkinDecorations(
                scene: .nightSky(SkinNightSky(
                    starColor: .Skin.Tsuki.Star.core,
                    haloColor: .Skin.Tsuki.Star.halo,
                    density: 0.55,
                    moon: true,
                    moonImage: .Skin.Tsuki.moon,
                    moonInk: palette.titleStroke,
                    moonBlush: semantic(.danger, .accent),
                    glows: [
                        SkinGlow(palette.shadow, at: UnitPoint(x: 0.7, y: 0.3), opacity: 0.22),
                        SkinGlow(semantic(.info, .accent), at: UnitPoint(x: 0.15, y: 0.85), opacity: 0.12),
                    ],
                )),
                glyphs: [
                    SkinGlyph("☾", .Skin.Tsuki.Star.core), SkinGlyph("✦", eyebrow), SkinGlyph("✧", eyebrow),
                    SkinGlyph("⋆", .Skin.Tsuki.Star.core), SkinGlyph("✩", accentMark),
                ],
                frameCorners: (SkinGlyph("☾", .Skin.Tsuki.Star.core), SkinGlyph("✦", eyebrow)),
                tapGlyph: SkinGlyph("✦", .Skin.Tsuki.Star.core),
            )
        case .astrelia:
            // Astrelia's `.starsky`: a dense white/blue field, gold stars.
            SkinDecorations(
                scene: .nightSky(SkinNightSky(
                    starColor: .Skin.Astrelia.Star.core,
                    haloColor: .Skin.Astrelia.Star.halo,
                    density: 1.0,
                    moon: false,
                    glows: [
                        SkinGlow(accentMark, at: UnitPoint(x: 0.5, y: -0.06), opacity: 0.16),
                        SkinGlow(eyebrow, at: UnitPoint(x: 0.1, y: 1.0), opacity: 0.11),
                        SkinGlow(accentMark, at: UnitPoint(x: 0.95, y: 1.0), opacity: 0.09),
                    ],
                )),
                glyphs: [
                    SkinGlyph("✦", semantic(.caution, .accent)), SkinGlyph("★", semantic(.caution, .accent)),
                    SkinGlyph("✧", .Skin.Astrelia.Star.core), SkinGlyph("⋆", .Skin.Astrelia.Star.core),
                    SkinGlyph("☾", semantic(.caution, .accent)), SkinGlyph("✦", accentMark),
                ],
                frameCorners: (SkinGlyph("✧", semantic(.caution, .accent)), SkinGlyph("⋆", .Skin.Astrelia.Star.core)),
                tapGlyph: SkinGlyph("✦", semantic(.caution, .accent)),
            )
        case .jellyfish:
            SkinDecorations(
                scene: .underwater(SkinUnderwater(
                    deep: .Skin.Jellyfish.Water.deep,
                    shallow: .Skin.Jellyfish.Water.shallow,
                    ray: .Skin.Jellyfish.Water.ray,
                    bubble: .Skin.Jellyfish.Water.bubble,
                    bells: [.Skin.Jellyfish.Jelly.violet, .Skin.Jellyfish.Jelly.cyan, .Skin.Jellyfish.Jelly.pink],
                )),
                glyphs: [],
                frameCorners: nil,
                // A bubble from every tap.
                tapGlyph: SkinGlyph("○", .Skin.Jellyfish.Water.bubble),
            )
        }
    }

    /// A dashed inner border inside every card — the site's `.frame::before`
    /// (`2px dashed var(--pink-hot)` inset 6px). `nil` for skins whose cards
    /// are plain surfaces.
    var cardInsetDash: Color? {
        switch self {
        case .elyPink: accentMark
        case .piru, .tsuki, .astrelia, .jellyfish: nil
        }
    }

    /// The corner of a small filled chip that is not drawn by ``SkinChrome``'s
    /// primitives (the white chips on the Library's gradient cards). `nil`
    /// keeps a capsule; an edged skin squares them like every other chip.
    var chipCornerRadius: CGFloat? {
        switch self {
        case .elyPink, .astrelia: 3
        case .piru, .tsuki, .jellyfish: nil
        }
    }

    /// The navigation large title's treatment. An edged skin fills it and
    /// gives it a hard drop like the site's `h1`; a soft skin gives it a glow.
    /// `nil` leaves the system's plain title.
    var titleOutline: SkinTitleOutline? {
        switch self {
        case .piru: nil
        // The site's `h1`: hot pink at night, near-black in pink mode, with a
        // hard drop (wine at night, hot pink in pink mode).
        case .elyPink: SkinTitleOutline(
            fill: palette.titleFill, stroke: palette.titleStroke,
            shadow: palette.titleShadow, shadowOffset: CGSize(width: 3, height: 3), shadowBlur: 0,
        )
        case .astrelia: SkinTitleOutline(
            fill: palette.titleFill, stroke: palette.titleStroke,
            shadow: palette.titleShadow, shadowOffset: CGSize(width: 3, height: 3), shadowBlur: 0,
        )
        // Soft skins: no outline, the label colour, a coloured glow beneath.
        case .tsuki, .jellyfish: SkinTitleOutline(
            fill: nil, stroke: nil,
            shadow: palette.titleShadow, shadowOffset: .zero, shadowBlur: 14,
        )
        }
    }

    // MARK: - Surface treatment

    /// How cards and capsules are drawn. The default skin keeps the app's
    /// scheme-adaptive material; an edged skin draws a solid fill with a stroke
    /// and a hard offset shadow; a soft skin draws a solid fill with a hairline
    /// and a coloured glow — never a black shadow.
    var surface: SkinSurface {
        switch self {
        case .piru: .glass
        case .elyPink: .edged(
            stroke: palette.stroke, strokeWidth: 2.5,
            shadow: palette.shadow, shadowOffset: CGSize(width: 3, height: 3),
        )
        case .astrelia: .edged(
            stroke: palette.stroke, strokeWidth: 2.5,
            shadow: palette.shadow, shadowOffset: CGSize(width: 4, height: 5),
        )
        case .tsuki: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 14)
        case .jellyfish: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 18)
        }
    }

    // MARK: - Type

    /// Applied once at the root. `nil` keeps the system default design; this
    /// reshapes every semantic text style in the app without touching call
    /// sites.
    ///
    /// **Must be `nil` for any skin with a custom face in ``typeface``.** A
    /// root `fontDesign` re-derives every SwiftUI font in the tree as a system
    /// font of that design — wrapped custom `UIFont`s included — so the display
    /// face would render only in UIKit's navigation bar and nowhere else.
    /// `SkinTypeTests` enforces the exclusion.
    var fontDesign: Font.Design? {
        switch self {
        case .piru, .elyPink, .astrelia: nil
        // Tsuki is `.rounded` throughout; the jellyfish skin borrows it.
        case .tsuki, .jellyfish: .rounded
        }
    }

    /// Custom families by role. Body copy always stays the system face (with
    /// ``fontDesign``): the CJK body fonts a skin might want run 4–9 MB per
    /// weight, and the app ships in three scripts. Display and label faces
    /// are small and carry most of a skin's character.
    var typeface: SkinTypeface {
        switch self {
        case .piru, .tsuki, .jellyfish: SkinTypeface(display: nil, label: nil)
        // Fredoka (variable, 159 KB) for titles; DotGothic16 (2 MB, includes
        // kana + JIS kanji) for chips and badges. Both SIL OFL, in Piru/Fonts.
        case .elyPink: SkinTypeface(display: "Fredoka", label: "DotGothic16")
        // Astrelia's site sets its titles in Fredoka too.
        case .astrelia: SkinTypeface(display: "Fredoka", label: nil)
        }
    }
}

// MARK: - Palette

/// One skin's colour tokens. Every member is a catalog symbol (or, for the
/// default skin, the un-namespaced token the app shipped with).
struct SkinPalette: Sendable {
    let accent: Color
    let accentMark: Color
    let onAccent: Color
    let secondaryLabel: Color
    let background: Color
    let cardBackground: Color
    let inputBackground: Color
    let eyebrow: Color
    /// Card edge (edged skins) or hairline (soft skins).
    let stroke: Color
    /// Hard offset shadow (edged skins) or glow (soft skins).
    let shadow: Color
    /// Large-title fill, read against the *background*, not the card.
    let titleFill: Color
    let titleStroke: Color
    let titleShadow: Color
    let danger: (text: Color, accent: Color)
    let caution: (text: Color, accent: Color)
    let success: (text: Color, accent: Color)
    let info: (text: Color, accent: Color)

    func semantic(_ role: SemanticRole, _ variant: SemanticVariant) -> Color {
        let pair = switch role {
        case .danger: danger
        case .caution: caution
        case .success: success
        case .info: info
        }
        return variant == .text ? pair.text : pair.accent
    }

    static let piru = SkinPalette(
        accent: .accent, accentMark: .accent, onAccent: .white,
        secondaryLabel: .Text.secondary,
        background: .Surface.background, cardBackground: .Surface.card, inputBackground: .Surface.input,
        eyebrow: .Text.secondary, stroke: .Text.secondary, shadow: .black,
        titleFill: .primary, titleStroke: .black, titleShadow: .black,
        danger: (.Semantic.Danger.text, .Semantic.Danger.accent),
        caution: (.Semantic.Caution.text, .Semantic.Caution.accent),
        success: (.Semantic.Success.text, .Semantic.Success.accent),
        info: (.Semantic.Info.text, .Semantic.Info.accent),
    )

    static let elyPink = SkinPalette(
        accent: .Skin.Elypink.Accent.text, accentMark: .Skin.Elypink.Accent.mark, onAccent: .Skin.Elypink.Accent.on,
        secondaryLabel: .Skin.Elypink.Text.secondary,
        background: .Skin.Elypink.Surface.background, cardBackground: .Skin.Elypink.Surface.card, inputBackground: .Skin.Elypink.Surface.input,
        eyebrow: .Skin.Elypink.eyebrow, stroke: .Skin.Elypink.stroke, shadow: .Skin.Elypink.shadow,
        titleFill: .Skin.Elypink.Title.fill, titleStroke: .Skin.Elypink.Title.stroke, titleShadow: .Skin.Elypink.Title.shadow,
        danger: (.Skin.Elypink.Semantic.Danger.text, .Skin.Elypink.Semantic.Danger.accent),
        caution: (.Skin.Elypink.Semantic.Caution.text, .Skin.Elypink.Semantic.Caution.accent),
        success: (.Skin.Elypink.Semantic.Success.text, .Skin.Elypink.Semantic.Success.accent),
        info: (.Skin.Elypink.Semantic.Info.text, .Skin.Elypink.Semantic.Info.accent),
    )

    static let tsuki = SkinPalette(
        accent: .Skin.Tsuki.Accent.text, accentMark: .Skin.Tsuki.Accent.mark, onAccent: .Skin.Tsuki.Accent.on,
        secondaryLabel: .Skin.Tsuki.Text.secondary,
        background: .Skin.Tsuki.Surface.background, cardBackground: .Skin.Tsuki.Surface.card, inputBackground: .Skin.Tsuki.Surface.input,
        eyebrow: .Skin.Tsuki.eyebrow, stroke: .Skin.Tsuki.stroke, shadow: .Skin.Tsuki.shadow,
        titleFill: .primary, titleStroke: .Skin.Tsuki.Title.stroke, titleShadow: .Skin.Tsuki.Title.shadow,
        danger: (.Skin.Tsuki.Semantic.Danger.text, .Skin.Tsuki.Semantic.Danger.accent),
        caution: (.Skin.Tsuki.Semantic.Caution.text, .Skin.Tsuki.Semantic.Caution.accent),
        success: (.Skin.Tsuki.Semantic.Success.text, .Skin.Tsuki.Semantic.Success.accent),
        info: (.Skin.Tsuki.Semantic.Info.text, .Skin.Tsuki.Semantic.Info.accent),
    )

    static let astrelia = SkinPalette(
        accent: .Skin.Astrelia.Accent.text, accentMark: .Skin.Astrelia.Accent.mark, onAccent: .Skin.Astrelia.Accent.on,
        secondaryLabel: .Skin.Astrelia.Text.secondary,
        background: .Skin.Astrelia.Surface.background, cardBackground: .Skin.Astrelia.Surface.card, inputBackground: .Skin.Astrelia.Surface.input,
        eyebrow: .Skin.Astrelia.eyebrow, stroke: .Skin.Astrelia.stroke, shadow: .Skin.Astrelia.shadow,
        titleFill: .Skin.Astrelia.Title.fill, titleStroke: .Skin.Astrelia.Title.stroke, titleShadow: .Skin.Astrelia.Title.shadow,
        danger: (.Skin.Astrelia.Semantic.Danger.text, .Skin.Astrelia.Semantic.Danger.accent),
        caution: (.Skin.Astrelia.Semantic.Caution.text, .Skin.Astrelia.Semantic.Caution.accent),
        success: (.Skin.Astrelia.Semantic.Success.text, .Skin.Astrelia.Semantic.Success.accent),
        info: (.Skin.Astrelia.Semantic.Info.text, .Skin.Astrelia.Semantic.Info.accent),
    )

    static let jellyfish = SkinPalette(
        accent: .Skin.Jellyfish.Accent.text, accentMark: .Skin.Jellyfish.Accent.mark, onAccent: .Skin.Jellyfish.Accent.on,
        secondaryLabel: .Skin.Jellyfish.Text.secondary,
        background: .Skin.Jellyfish.Surface.background, cardBackground: .Skin.Jellyfish.Surface.card, inputBackground: .Skin.Jellyfish.Surface.input,
        eyebrow: .Skin.Jellyfish.eyebrow, stroke: .Skin.Jellyfish.stroke, shadow: .Skin.Jellyfish.shadow,
        titleFill: .primary, titleStroke: .Skin.Jellyfish.Title.stroke, titleShadow: .Skin.Jellyfish.Title.shadow,
        danger: (.Skin.Jellyfish.Semantic.Danger.text, .Skin.Jellyfish.Semantic.Danger.accent),
        caution: (.Skin.Jellyfish.Semantic.Caution.text, .Skin.Jellyfish.Semantic.Caution.accent),
        success: (.Skin.Jellyfish.Semantic.Success.text, .Skin.Jellyfish.Semantic.Success.accent),
        info: (.Skin.Jellyfish.Semantic.Info.text, .Skin.Jellyfish.Semantic.Info.accent),
    )
}

/// Font family names a skin bundles, by role. `nil` means the system face.
struct SkinTypeface: Equatable, Sendable {
    /// largeTitle · title · title2 · title3 · headline, and navigation titles.
    let display: String?
    /// Chips, badges — small categorical labels, never body copy or data.
    let label: String?
}

/// The L1 status roles. A closed set — see `design-system/README.md`.
enum SemanticRole: CaseIterable, Sendable {
    case danger, caution, success, info
}

/// `text` is small copy (gated 4.5:1); `accent` is a standalone mark (3:1).
enum SemanticVariant: CaseIterable, Sendable {
    case text, accent
}

// MARK: - Decorations

/// A skin's decoration set: the scene `SkinBackdrop` draws behind every
/// screen, the glyph stickers it scatters over it, the pair that sits on a
/// glance card's corners, and the one that floats up from a tap.
struct SkinDecorations: Sendable {
    let scene: SkinScene
    /// Stickers scattered over the scene. Empty for none.
    let glyphs: [SkinGlyph]
    /// (top-right, bottom-left) on the large cards. `nil` for none.
    let frameCorners: (SkinGlyph, SkinGlyph)?
    /// Spawned at every tap by `TapTrail`. `nil` for none.
    let tapGlyph: SkinGlyph?
}

/// What `SkinBackdrop` paints under the stickers.
enum SkinScene: Sendable {
    /// ely.pink: a warm glow at the top and a faint dotted ground; the
    /// stickers carry the scene.
    case stickers
    /// A night sky: a twinkling, haloed starfield over nebula glows.
    case nightSky(SkinNightSky)
    /// Deep water: a depth gradient, light rays, rising bubbles, and
    /// jellyfish swimming up.
    case underwater(SkinUnderwater)
}

/// A radial glow on the ground: colour, centre, peak opacity.
struct SkinGlow: Sendable {
    let color: Color
    let center: UnitPoint
    let opacity: Double

    init(_ color: Color, at center: UnitPoint, opacity: Double) {
        self.color = color
        self.center = center
        self.opacity = opacity
    }
}

struct SkinNightSky: Sendable {
    let starColor: Color
    let haloColor: Color
    /// 1.0 is Astrelia's dense field; Tsuki is sparser.
    let density: Double
    /// A sleeping crescent moon.
    let moon: Bool
    /// The moon as drawn art — Tsuki's own icon, lifted with its glow — or
    /// `nil` to draw a crescent by hand.
    var moonImage: ImageResource? = nil
    /// The hand-drawn crescent's closed eyes and smile, and its blush.
    var moonInk: Color = .black
    var moonBlush: Color = .pink
    let glows: [SkinGlow]
}

struct SkinUnderwater: Sendable {
    /// The water column, bottom to top.
    let deep: Color
    let shallow: Color
    /// Light rays from the surface.
    let ray: Color
    let bubble: Color
    /// Bell colours the jellyfish cycle through.
    let bells: [Color]
}

/// One sticker glyph in a token colour.
struct SkinGlyph: Sendable {
    let symbol: String
    let color: Color

    init(_ symbol: String, _ color: Color) {
        self.symbol = symbol
        self.color = color
    }
}

/// A treated navigation title. Applied through UIKit's appearance proxy by
/// `SkinNavigationTitles` (large titles are drawn by the navigation bar, not
/// SwiftUI) and by `.skinHeroTitle()` on SwiftUI hero titles.
struct SkinTitleOutline: Sendable {
    /// `nil` keeps the label colour.
    let fill: Color?
    /// `nil` for no outline. Only the SwiftUI hero draws it — see
    /// `SkinNavigationTitles` for why the bar never strokes.
    let stroke: Color?
    let shadow: Color
    let shadowOffset: CGSize
    /// 0 for a hard drop; larger for a glow.
    let shadowBlur: CGFloat
}

/// The card treatment a skin asks for. See ``ThemedBackground``.
enum SkinSurface: Equatable, Sendable {
    /// `.ultraThinMaterial` in light, the skin's `cardBackground` in dark —
    /// the treatment the app shipped with.
    case glass
    /// Solid `cardBackground` in both schemes, a `strokeWidth` border in
    /// `stroke`, and a hard (unblurred) shadow of `shadow` offset by `shadowOffset`.
    case edged(stroke: Color, strokeWidth: CGFloat, shadow: Color, shadowOffset: CGSize)
    /// Solid `cardBackground`, a 1pt hairline in `stroke` at low opacity, and
    /// a coloured `glow` of `glowRadius` — never a black shadow.
    case soft(stroke: Color, glow: Color, glowRadius: CGFloat)
}

/// The user's light/dark override. `system` defers to iOS.
enum SkinColorScheme: String, CaseIterable, Identifiable, Sendable {
    case system, light, dark

    var id: String { rawValue }

    /// Distinct from the dose-tier key `"Light"` (轻度), which is a different word.
    var displayName: LocalizedStringResource {
        switch self {
        case .system: "Follow System"
        case .light: "Light Mode"
        case .dark: "Dark Mode"
        }
    }

    /// What to hand `preferredColorScheme`. `nil` means follow the system.
    var colorScheme: ColorScheme? {
        switch self {
        case .system: nil
        case .light: .light
        case .dark: .dark
        }
    }
}

/// UserDefaults keys for the skin preference. One source of truth so the app's
/// `SkinStore` and the extensions read the same choice. Stored in the app group
/// suite so the widget and Live Activity can honour it.
nonisolated enum SkinDefaults {
    static let suite = "group.dev.yumeji.piru"
    static let skinKey = "skin"
    static let colorSchemeKey = "skinColorScheme"
    static let decorationsKey = "skinDecorations"
    static let skinDefault: Skin = .piru
    static let colorSchemeDefault: SkinColorScheme = .system
    static let decorationsDefault = true

    /// The persisted skin, for targets without a `SkinStore` (widgets). Falls
    /// back to the default when the stored value names a skin this build lacks.
    static func storedSkin(in defaults: UserDefaults? = UserDefaults(suiteName: suite)) -> Skin {
        guard let raw = defaults?.string(forKey: skinKey), let skin = Skin(rawValue: raw) else {
            return skinDefault
        }
        return skin
    }
}
