import SwiftUI

/// A skin is a named visual identity for the app: a palette, a surface
/// treatment, a type design, and a decoration scene. It is *not* a light/dark
/// pair — every skin carries both appearances (and high-contrast variants) in
/// the asset catalog, so the system's colour scheme keeps working inside any skin.
///
/// ## Where a skin's colours live
///
/// In `Shared/Assets.xcassets`, under `skin/<id>/…`, generated by
/// `design-system/color/generate_colorsets.py` from `palette-skins.json`
/// exactly like the default tokens. Each skin builds one ``SkinPalette`` from
/// the Xcode-generated symbols for its namespace — never a string lookup, so
/// a missing colorset is a compile error, and `ColorContrastTests` gates every
/// skin against the same floors as the default.
///
/// The default skin reads the un-namespaced tokens (`surface/card`,
/// `text/secondary`, `AccentColor`) — the catalog the app shipped with, untouched.
///
/// ## What a skin never touches
///
/// Graphs. The timeline spine, sparklines and PK charts read `series.color`
/// and `Color.primary` with their own opacities and never see `Theme`, so a
/// skin cannot restyle them. Per-substance identity colours (L3) and the L2
/// encoding scales (routes, dose tiers, phases) are likewise not a skin's to
/// change — only their surrounding chrome is.
///
/// Lives in `Shared/` so the widget and Live Activity targets can resolve the
/// active skin's colours from the same catalog; the store that *chooses* the
/// skin (`SkinStore`) is app-only.
enum Skin: String, CaseIterable, Identifiable, Sendable {
    /// The app's own look: soft pink light, hot pink dark, Liquid Glass.
    case piru
    /// Graphite — neutral grays, nothing moving. For people who want none of it.
    case graphite
    /// Linen — warm paper and charcoal, quiet.
    case linen
    /// Slate — cool blue-gray, quiet.
    case slate
    /// ely.pink — the author's homepage. Night (plum-black, hot pink, lilac,
    /// mint) and pink (cream cards on a pink ground with near-black edges).
    /// Solid edged cards with hard offset shadows; nothing tilts.
    case elyPink
    /// Tsuki — the author's journaling app. Deep purple night, lavender
    /// hairlines, glows instead of shadows, a sleeping moon and drifting stars.
    case tsuki
    /// Starfield — Astrelia's steel-blue sky: edged cards, gold stars, a dense
    /// twinkling field.
    case astrelia
    /// Jellyfish — deep water. Bioluminescent cyan and violet, soft glowing
    /// cards, bubbles rising and jellyfish swimming up behind everything.
    case jellyfish
    /// Paper garden — Origami's washi and Kaze's raked sand: matte paper,
    /// washi red, stones and moss, sakura petals.
    case paperGarden
    /// Hotaru — the author's ambient-art app. Fireflies over a dark meadow,
    /// an aurora at the top.
    case hotaru
    /// Yuki — the author's Pomodoro. Periwinkle, snow and frost, dual.
    case yuki
    /// Hebi arcade — the snake game's Neon City: magenta and cyan phosphor,
    /// a perspective grid, a pixel face.
    case hebi
    /// Kumo — the author's weather app. A sky that follows the real time of
    /// day and the season, frosted cards that let it through.
    case kumo
    /// dose.wiki — the partner encyclopedia's plum and fuchsia, their dose-tier
    /// ramp as the semantic colours, their molecule ring behind everything.
    case doseWiki

    var id: String { rawValue }

    /// Picker name. Localized like every user-facing string.
    var displayName: LocalizedStringResource {
        switch self {
        case .piru: "Piru"
        case .graphite: "Graphite"
        case .linen: "Linen"
        case .slate: "Slate"
        case .elyPink: "ely.pink"
        case .tsuki: "Tsuki"
        case .astrelia: "Starfield"
        case .jellyfish: "Jellyfish"
        case .paperGarden: "Paper Garden"
        case .hotaru: "Hotaru"
        case .yuki: "Yuki"
        case .hebi: "Hebi Arcade"
        case .kumo: "Kumo"
        case .doseWiki: "dose.wiki"
        }
    }

    /// One line under the name in the picker.
    var tagline: LocalizedStringResource {
        switch self {
        case .piru: "Soft pink, hot pink, liquid glass"
        case .graphite: "Neutral grays, nothing moving"
        case .linen: "Warm paper and charcoal, quiet"
        case .slate: "Cool blue-gray, quiet"
        case .elyPink: "Night and pink, stickers and pixels"
        case .tsuki: "Deep purple night, a sleeping moon"
        case .astrelia: "Steel blue and gold under a thousand stars"
        case .jellyfish: "Deep water, bioluminescence, jellyfish"
        case .paperGarden: "Washi, raked sand, sakura"
        case .hotaru: "Fireflies and an aurora"
        case .yuki: "Periwinkle, snow and frost"
        case .hebi: "Neon City on a CRT"
        case .kumo: "A sky that follows the day"
        case .doseWiki: "Plum and fuchsia, from the open encyclopedia"
        }
    }

    // MARK: - Current

    /// The skin the app is showing, readable from `Shared/` code that cannot
    /// see `SkinStore`. The app installs a provider that reads the observable
    /// store (so reads inside a `body` are tracked); before that, and in the
    /// extensions, it falls back to the persisted choice.
    nonisolated static var current: Skin { currentProvider() }

    /// Replaced once by `SkinStore.activate()` at launch; read on the main
    /// thread from view bodies. `nonisolated(unsafe)` because the members of
    /// this `Sendable` enum are nonisolated and the write happens before any
    /// view exists.
    nonisolated(unsafe) static var currentProvider: @Sendable () -> Skin = { SkinDefaults.storedSkin() }

    // MARK: - Palette

    /// The skin's tokens, from its catalog namespace.
    var palette: SkinPalette {
        switch self {
        case .piru: .piru
        case .graphite: .graphite
        case .linen: .linen
        case .slate: .slate
        case .elyPink: .elyPink
        case .tsuki: .tsuki
        case .astrelia: .astrelia
        case .jellyfish: .jellyfish
        case .paperGarden: .paperGarden
        case .hotaru: .hotaru
        case .yuki: .yuki
        case .hebi: .hebi
        case .kumo: .kumo
        case .doseWiki: .doseWiki
        }
    }

    /// Label colour on an ``accentMark`` fill (buttons, tab stickers). Gated
    /// 4.5:1 against ``accent``. The default skin's white-on-accent is the
    /// system's own choice for `.glassProminent`.
    var onAccent: Color { palette.onAccent }

    /// Brand accent and control tint. **Text-safe** in every skin: the app uses
    /// one token for both copy and marks, so where a skin's vivid mark colour
    /// fails as small text (ely.pink's hot pink on cream, 2.9:1) this is the
    /// darker `accent/text` twin and ``accentMark`` carries the vivid one.
    var accent: Color { palette.accent }

    /// The vivid accent for standalone marks: rings, glows, selection fills
    /// under white text. Gated at the 3:1 non-text floor, never used as copy.
    var accentMark: Color { palette.accentMark }

    /// De-emphasized body text. Gated AA 4.5:1 on `cardBackground`.
    var secondaryLabel: Color { palette.secondaryLabel }

    /// Page backdrop.
    var background: Color { palette.background }

    /// Card / raised surface fill.
    var cardBackground: Color { palette.cardBackground }

    /// Text-field and other input fills.
    var inputBackground: Color { palette.inputBackground }

    /// Eyebrows, section labels, sticker shadows — the skin's "wine". The
    /// default skin has no such role and uses secondary text.
    var eyebrow: Color { palette.eyebrow }

    /// Status colours. Skins may re-seed the L1 ladder; the roles and the
    /// `text` / `accent` split are fixed by the design system.
    func semantic(_ role: SemanticRole, _ variant: SemanticVariant) -> Color {
        palette.semantic(role, variant)
    }

    // MARK: - Decorations

    /// The decoration layer behind every screen. `nil` for skins that keep
    /// the ground plain. Colours come from the skin's own tokens; the app
    /// draws them, so nothing here is content.
    var decorations: SkinDecorations? {
        switch self {
        case .piru, .graphite, .linen, .slate:
            nil
        case .elyPink:
            SkinDecorations(
                scene: .stickers,
                glyphs: [
                    SkinGlyph("★", semantic(.caution, .accent)), SkinGlyph("☆", semantic(.caution, .accent)),
                    SkinGlyph("✦", .white), SkinGlyph("✧", .white),
                    SkinGlyph("♡", accentMark), SkinGlyph("♥", accentMark), SkinGlyph("✿", accentMark),
                    SkinGlyph("✚", eyebrow), SkinGlyph("♠", eyebrow), SkinGlyph("✗", eyebrow),
                    SkinGlyph("✦", semantic(.success, .accent)),
                ],
                // The site's `.term::before/::after`: ✧ on the top-right edge, ♡
                // on the bottom-left.
                frameCorners: (SkinGlyph("✧", semantic(.caution, .accent)), SkinGlyph("♡", accentMark)),
                // The site's cursor trail: a ♡ that floats up from every tap.
                tapGlyph: SkinGlyph("♡", accentMark),
            )
        case .tsuki:
            // Tsuki's `DreamyEffects`: a sparse field of haloed stars over two
            // nebula glows, and its sleeping moon.
            SkinDecorations(
                scene: .nightSky(SkinNightSky(
                    starColor: .Skin.Tsuki.Star.core,
                    haloColor: .Skin.Tsuki.Star.halo,
                    density: 0.55,
                    seed: 0x7511,
                    moon: true,
                    moonImage: .Skin.Tsuki.moon,
                    moonInk: palette.titleStroke,
                    moonBlush: semantic(.danger, .accent),
                    glows: [
                        SkinGlow(palette.shadow, at: UnitPoint(x: 0.7, y: 0.3), opacity: 0.22),
                        SkinGlow(semantic(.info, .accent), at: UnitPoint(x: 0.15, y: 0.85), opacity: 0.12),
                    ],
                )),
                glyphs: [
                    SkinGlyph("☾", .Skin.Tsuki.Star.core), SkinGlyph("✦", eyebrow), SkinGlyph("✧", eyebrow),
                    SkinGlyph("⋆", .Skin.Tsuki.Star.core), SkinGlyph("✩", accentMark),
                ],
                frameCorners: (SkinGlyph("☾", .Skin.Tsuki.Star.core), SkinGlyph("✦", eyebrow)),
                tapGlyph: SkinGlyph("✦", .Skin.Tsuki.Star.core),
            )
        case .astrelia:
            // Astrelia's `.starsky`: a dense white/blue field, gold stars.
            SkinDecorations(
                scene: .nightSky(SkinNightSky(
                    starColor: .Skin.Astrelia.Star.core,
                    haloColor: .Skin.Astrelia.Star.halo,
                    density: 1.0,
                    seed: 0xA57A,
                    milkyWay: true,
                    moon: false,
                    glows: [
                        SkinGlow(accentMark, at: UnitPoint(x: 0.5, y: -0.06), opacity: 0.16),
                        SkinGlow(eyebrow, at: UnitPoint(x: 0.1, y: 1.0), opacity: 0.11),
                        SkinGlow(accentMark, at: UnitPoint(x: 0.95, y: 1.0), opacity: 0.09),
                    ],
                )),
                glyphs: [
                    SkinGlyph("✦", semantic(.caution, .accent)), SkinGlyph("★", semantic(.caution, .accent)),
                    SkinGlyph("✧", .Skin.Astrelia.Star.core), SkinGlyph("⋆", .Skin.Astrelia.Star.core),
                    SkinGlyph("☾", semantic(.caution, .accent)), SkinGlyph("✦", accentMark),
                ],
                frameCorners: (SkinGlyph("✧", semantic(.caution, .accent)), SkinGlyph("⋆", .Skin.Astrelia.Star.core)),
                tapGlyph: SkinGlyph("✦", semantic(.caution, .accent)),
            )
        case .jellyfish:
            SkinDecorations(
                scene: .underwater(SkinUnderwater(
                    deep: .Skin.Jellyfish.Water.deep,
                    shallow: .Skin.Jellyfish.Water.shallow,
                    ray: .Skin.Jellyfish.Water.ray,
                    bubble: .Skin.Jellyfish.Water.bubble,
                    bells: [.Skin.Jellyfish.Jelly.violet, .Skin.Jellyfish.Jelly.cyan, .Skin.Jellyfish.Jelly.pink],
                )),
                glyphs: [],
                frameCorners: nil,
                // A bubble from every tap.
                tapGlyph: SkinGlyph("○", .Skin.Jellyfish.Water.bubble),
            )
        case .paperGarden:
            SkinDecorations(
                scene: .paper(SkinPaperGarden(
                    sand1: .Skin.Papergarden.Garden.sand1, sand2: .Skin.Papergarden.Garden.sand2,
                    groove: .Skin.Papergarden.Garden.groove, stone: .Skin.Papergarden.Garden.stone,
                    moss: .Skin.Papergarden.Garden.moss, petal: .Skin.Papergarden.Garden.petal,
                    firefly: .Skin.Papergarden.Garden.firefly, grain: palette.shadow,
                )),
                glyphs: [
                    SkinGlyph("✿", .Skin.Papergarden.Garden.petal), SkinGlyph("❀", .Skin.Papergarden.Garden.petal),
                    SkinGlyph("✾", semantic(.caution, .accent)), SkinGlyph("〜", palette.stroke),
                ],
                frameCorners: (SkinGlyph("✿", .Skin.Papergarden.Garden.petal), SkinGlyph("❀", semantic(.caution, .accent))),
                tapGlyph: SkinGlyph("✿", .Skin.Papergarden.Garden.petal),
            )
        case .hotaru:
            SkinDecorations(
                scene: .fireflies(SkinFireflies(
                    core: .Skin.Hotaru.Night.core, glow: .Skin.Hotaru.Night.glow,
                    fog: .Skin.Hotaru.Night.fog, tree: .Skin.Hotaru.Night.tree,
                    aurora: [.Skin.Hotaru.Night.aurora1, .Skin.Hotaru.Night.aurora2, .Skin.Hotaru.Night.aurora3, .Skin.Hotaru.Night.aurora4],
                )),
                glyphs: [SkinGlyph("✦", .Skin.Hotaru.Night.core), SkinGlyph("✧", .Skin.Hotaru.Night.glow), SkinGlyph("·", .Skin.Hotaru.Night.core)],
                frameCorners: nil,
                tapGlyph: SkinGlyph("✦", .Skin.Hotaru.Night.glow),
            )
        case .yuki:
            SkinDecorations(
                scene: .snow(SkinSnow(flake: .Skin.Yuki.Snow.flake, frost: .Skin.Yuki.Snow.frost)),
                glyphs: [SkinGlyph("❄", .Skin.Yuki.Snow.flake), SkinGlyph("✻", .Skin.Yuki.Snow.frost), SkinGlyph("❅", accentMark)],
                frameCorners: (SkinGlyph("❄", .Skin.Yuki.Snow.flake), SkinGlyph("✻", .Skin.Yuki.Snow.frost)),
                tapGlyph: SkinGlyph("❄", .Skin.Yuki.Snow.flake),
            )
        case .hebi:
            SkinDecorations(
                scene: .arcade(SkinArcade(
                    grid: .Skin.Hebi.Arcade.grid, wall: .Skin.Hebi.Arcade.wall, border: .Skin.Hebi.Arcade.border,
                    snake: .Skin.Hebi.Arcade.snake, snakeBody: .Skin.Hebi.Arcade.snakeBody,
                    food: .Skin.Hebi.Arcade.food, star: .Skin.Hebi.Arcade.star,
                )),
                glyphs: [
                    SkinGlyph("▪", accentMark), SkinGlyph("▴", .Skin.Hebi.Arcade.food),
                    SkinGlyph("●", semantic(.caution, .accent)), SkinGlyph("✦", accentMark),
                ],
                frameCorners: (SkinGlyph("✦", accentMark), SkinGlyph("▪", .Skin.Hebi.Arcade.food)),
                tapGlyph: SkinGlyph("▪", .Skin.Hebi.Arcade.food),
            )
        case .kumo:
            SkinDecorations(
                scene: .sky(SkinSky(
                    night: (.Skin.Kumo.Sky.night1, .Skin.Kumo.Sky.night2),
                    day: (.Skin.Kumo.Sky.day1, .Skin.Kumo.Sky.day2),
                    sunset: (.Skin.Kumo.Sky.sunset1, .Skin.Kumo.Sky.sunset2),
                    cloud: .Skin.Kumo.Sky.cloud, star: .Skin.Kumo.Sky.star, rain: .Skin.Kumo.Sky.rain,
                    sun: .Skin.Kumo.Sky.sun, moon: .Skin.Kumo.Sky.moon,
                    auroraPurple: semantic(.info, .accent), auroraCyan: accentMark,
                )),
                glyphs: [
                    SkinGlyph("☁", .Skin.Kumo.Sky.cloud), SkinGlyph("✦", semantic(.caution, .accent)),
                    SkinGlyph("☾", .Skin.Kumo.Sky.moon), SkinGlyph("✧", .Skin.Kumo.Sky.sun),
                ],
                frameCorners: (SkinGlyph("☁", .Skin.Kumo.Sky.cloud), SkinGlyph("✦", semantic(.caution, .accent))),
                tapGlyph: SkinGlyph("✦", semantic(.caution, .accent)),
            )
        case .doseWiki:
            // The site is quiet: its page halos, its molecule ring, no stickers.
            SkinDecorations(
                scene: .molecule(SkinMolecule(
                    image: .Skin.Dosewiki.molecule,
                    ink: .Skin.Dosewiki.Molecule.ink,
                    halos: [
                        SkinGlow(.Skin.Dosewiki.Halo.top, at: UnitPoint(x: 0.5, y: 0), opacity: 0.16),
                        SkinGlow(.Skin.Dosewiki.Halo.left, at: UnitPoint(x: 0, y: 0.5), opacity: 0.09),
                        SkinGlow(.Skin.Dosewiki.Halo.right, at: UnitPoint(x: 1, y: 0.6), opacity: 0.08),
                        SkinGlow(.Skin.Dosewiki.Halo.bottom, at: UnitPoint(x: 0.5, y: 1), opacity: 0.07),
                    ],
                )),
                glyphs: [],
                frameCorners: nil,
                tapGlyph: nil,
            )
        }
    }

    /// A dashed inner border inside every card — the site's `.frame::before`
    /// (`2px dashed var(--pink-hot)` inset 6px). `nil` for skins whose cards
    /// are plain surfaces.
    var cardInsetDash: Color? {
        switch self {
        case .elyPink: accentMark
        case .piru, .graphite, .linen, .slate, .tsuki, .astrelia, .jellyfish, .paperGarden, .hotaru, .yuki, .hebi, .kumo, .doseWiki: nil
        }
    }

    /// The corner of a small filled chip that is not drawn by ``SkinChrome``'s
    /// primitives (the white chips on the Library's gradient cards). `nil`
    /// keeps a capsule; an edged skin squares them like every other chip.
    var chipCornerRadius: CGFloat? {
        switch self {
        case .elyPink, .astrelia: 3
        case .paperGarden: 2
        case .hebi: 0
        case .piru, .graphite, .linen, .slate, .tsuki, .jellyfish, .hotaru, .yuki, .kumo, .doseWiki: nil
        }
    }

    /// The navigation large title's treatment. An edged skin fills it and
    /// gives it a hard drop like the site's `h1`; a soft skin gives it a glow.
    /// `nil` leaves the system's plain title.
    var titleOutline: SkinTitleOutline? {
        switch self {
        // dose.wiki's wordmark is flat; only `.wiki` takes the accent.
        case .piru, .graphite, .linen, .slate, .doseWiki: nil
        // The site's `h1`: hot pink at night, near-black in pink mode, with a
        // hard drop (wine at night, hot pink in pink mode).
        case .elyPink: SkinTitleOutline(
            fill: palette.titleFill, stroke: palette.titleStroke,
            shadow: palette.titleShadow, shadowOffset: CGSize(width: 3, height: 3), shadowBlur: 0,
        )
        case .astrelia: SkinTitleOutline(
            fill: palette.titleFill, stroke: palette.titleStroke,
            shadow: palette.titleShadow, shadowOffset: CGSize(width: 3, height: 3), shadowBlur: 0,
        )
        // Soft skins: no outline, the label colour, a coloured glow beneath.
        case .tsuki, .jellyfish, .hotaru, .yuki, .kumo: SkinTitleOutline(
            fill: nil, stroke: nil,
            shadow: palette.titleShadow, shadowOffset: .zero, shadowBlur: 14,
        )
        // Ink with a hard sakura drop, no outline: a stamp on paper.
        case .paperGarden: SkinTitleOutline(
            fill: palette.titleFill, stroke: nil,
            shadow: palette.titleShadow, shadowOffset: CGSize(width: 2, height: 2), shadowBlur: 0,
        )
        // A neon sign: cyan tube, magenta glow.
        case .hebi: SkinTitleOutline(
            fill: palette.titleFill, stroke: nil,
            shadow: palette.titleShadow, shadowOffset: .zero, shadowBlur: 10,
        )
        }
    }

    // MARK: - Surface treatment

    /// How cards and capsules are drawn. The default skin keeps the app's
    /// scheme-adaptive material; an edged skin draws a solid fill with a stroke
    /// and a hard offset shadow; a soft skin draws a solid fill with a hairline
    /// and a coloured glow — never a black shadow.
    var surface: SkinSurface {
        switch self {
        case .piru, .graphite: .glass
        case .linen: .paper(stroke: palette.stroke, grain: palette.shadow)
        case .slate: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 10)
        case .elyPink: .edged(
            stroke: palette.stroke, strokeWidth: 2.5,
            shadow: palette.shadow, shadowOffset: CGSize(width: 3, height: 3),
        )
        case .astrelia: .edged(
            stroke: palette.stroke, strokeWidth: 2.5,
            shadow: palette.shadow, shadowOffset: CGSize(width: 4, height: 5),
        )
        case .tsuki: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 14)
        case .jellyfish: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 18)
        case .hotaru: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 16)
        case .yuki: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 12)
        case .paperGarden: .paper(stroke: palette.stroke, grain: palette.shadow)
        case .hebi: .neon(stroke: palette.stroke, glow: palette.shadow)
        case .kumo: .frosted(stroke: palette.stroke, highlight: palette.shadow)
        // Their cards: a fuchsia hairline over a plum panel, a soft dark shadow.
        case .doseWiki: .soft(stroke: palette.stroke, glow: palette.shadow, glowRadius: 12)
        }
    }

    // MARK: - Type

    /// Applied once at the root. `nil` keeps the system default design; this
    /// reshapes every semantic text style in the app without touching call
    /// sites.
    ///
    /// **Must be `nil` for any skin with a custom face in ``typeface``.** A
    /// root `fontDesign` re-derives every SwiftUI font in the tree as a system
    /// font of that design — wrapped custom `UIFont`s included — so the display
    /// face would render only in UIKit's navigation bar and nowhere else.
    /// `SkinTypeTests` enforces the exclusion.
    var fontDesign: Font.Design? {
        switch self {
        case .piru, .graphite, .linen, .slate, .elyPink, .astrelia, .paperGarden, .hotaru, .hebi, .kumo, .doseWiki: nil
        // Tsuki is `.rounded` throughout; the jellyfish skin borrows it, and
        // Yuki's ultralight rounded timer is its whole identity.
        case .tsuki, .jellyfish, .yuki: .rounded
        }
    }

    /// Custom families by role. Body copy always stays the system face (with
    /// ``fontDesign``): the CJK body fonts a skin might want run 4–9 MB per
    /// weight, and the app ships in three scripts. Display and label faces
    /// are small and carry most of a skin's character.
    var typeface: SkinTypeface {
        switch self {
        case .piru, .graphite, .linen, .slate, .tsuki, .jellyfish, .yuki, .hotaru, .kumo: SkinTypeface(display: nil, label: nil)
        // Fredoka (variable, 159 KB) for titles; DotGothic16 (2 MB, includes
        // kana + JIS kanji) for chips and badges. Both SIL OFL, in Piru/Fonts.
        case .elyPink: SkinTypeface(display: "Fredoka", label: "DotGothic16")
        // Astrelia's site sets its titles in Fredoka too.
        case .astrelia: SkinTypeface(display: "Fredoka", label: nil)
        // Fraunces (variable), a soft serif for paper.
        case .paperGarden: SkinTypeface(display: "Fraunces", label: nil)
        // Press Start 2P is set wide; scaled down so a large title fits the bar.
        case .hebi: SkinTypeface(display: "Press Start 2P", label: "Press Start 2P", displayScale: 0.72)
        // Saira (variable, OFL): the squarish geometric sans closest to their
        // wordmark, which the site's font loader hides. Set a touch wide.
        case .doseWiki: SkinTypeface(display: "Saira", label: nil, displayScale: 0.94)
        }
    }
}

// MARK: - Palette

/// One skin's colour tokens. Every member is a catalog symbol (or, for the
/// default skin, the un-namespaced token the app shipped with).
struct SkinPalette: Sendable {
    let accent: Color
    let accentMark: Color
    let onAccent: Color
    let secondaryLabel: Color
    let background: Color
    let cardBackground: Color
    let inputBackground: Color
    let eyebrow: Color
    /// Card edge (edged skins) or hairline (soft skins).
    let stroke: Color
    /// Hard offset shadow (edged skins) or glow (soft skins).
    let shadow: Color
    /// Large-title fill, read against the *background*, not the card.
    let titleFill: Color
    let titleStroke: Color
    let titleShadow: Color
    let danger: (text: Color, accent: Color)
    let caution: (text: Color, accent: Color)
    let success: (text: Color, accent: Color)
    let info: (text: Color, accent: Color)

    func semantic(_ role: SemanticRole, _ variant: SemanticVariant) -> Color {
        let pair = switch role {
        case .danger: danger
        case .caution: caution
        case .success: success
        case .info: info
        }
        return variant == .text ? pair.text : pair.accent
    }

    static let graphite = SkinPalette(
        accent: .Skin.Graphite.Accent.text, accentMark: .Skin.Graphite.Accent.mark, onAccent: .Skin.Graphite.Accent.on,
        secondaryLabel: .Skin.Graphite.Text.secondary,
        background: .Skin.Graphite.Surface.background, cardBackground: .Skin.Graphite.Surface.card, inputBackground: .Skin.Graphite.Surface.input,
        eyebrow: .Skin.Graphite.eyebrow, stroke: .Skin.Graphite.stroke, shadow: .Skin.Graphite.shadow,
        titleFill: .primary, titleStroke: .Skin.Graphite.Title.stroke, titleShadow: .Skin.Graphite.Title.shadow,
        danger: (.Skin.Graphite.Semantic.Danger.text, .Skin.Graphite.Semantic.Danger.accent),
        caution: (.Skin.Graphite.Semantic.Caution.text, .Skin.Graphite.Semantic.Caution.accent),
        success: (.Skin.Graphite.Semantic.Success.text, .Skin.Graphite.Semantic.Success.accent),
        info: (.Skin.Graphite.Semantic.Info.text, .Skin.Graphite.Semantic.Info.accent),
    )

    static let linen = SkinPalette(
        accent: .Skin.Linen.Accent.text, accentMark: .Skin.Linen.Accent.mark, onAccent: .Skin.Linen.Accent.on,
        secondaryLabel: .Skin.Linen.Text.secondary,
        background: .Skin.Linen.Surface.background, cardBackground: .Skin.Linen.Surface.card, inputBackground: .Skin.Linen.Surface.input,
        eyebrow: .Skin.Linen.eyebrow, stroke: .Skin.Linen.stroke, shadow: .Skin.Linen.shadow,
        titleFill: .primary, titleStroke: .Skin.Linen.Title.stroke, titleShadow: .Skin.Linen.Title.shadow,
        danger: (.Skin.Linen.Semantic.Danger.text, .Skin.Linen.Semantic.Danger.accent),
        caution: (.Skin.Linen.Semantic.Caution.text, .Skin.Linen.Semantic.Caution.accent),
        success: (.Skin.Linen.Semantic.Success.text, .Skin.Linen.Semantic.Success.accent),
        info: (.Skin.Linen.Semantic.Info.text, .Skin.Linen.Semantic.Info.accent),
    )

    static let slate = SkinPalette(
        accent: .Skin.Slate.Accent.text, accentMark: .Skin.Slate.Accent.mark, onAccent: .Skin.Slate.Accent.on,
        secondaryLabel: .Skin.Slate.Text.secondary,
        background: .Skin.Slate.Surface.background, cardBackground: .Skin.Slate.Surface.card, inputBackground: .Skin.Slate.Surface.input,
        eyebrow: .Skin.Slate.eyebrow, stroke: .Skin.Slate.stroke, shadow: .Skin.Slate.shadow,
        titleFill: .primary, titleStroke: .Skin.Slate.Title.stroke, titleShadow: .Skin.Slate.Title.shadow,
        danger: (.Skin.Slate.Semantic.Danger.text, .Skin.Slate.Semantic.Danger.accent),
        caution: (.Skin.Slate.Semantic.Caution.text, .Skin.Slate.Semantic.Caution.accent),
        success: (.Skin.Slate.Semantic.Success.text, .Skin.Slate.Semantic.Success.accent),
        info: (.Skin.Slate.Semantic.Info.text, .Skin.Slate.Semantic.Info.accent),
    )

    static let piru = SkinPalette(
        accent: .accent, accentMark: .accent, onAccent: .white,
        secondaryLabel: .Text.secondary,
        background: .Surface.background, cardBackground: .Surface.card, inputBackground: .Surface.input,
        eyebrow: .Text.secondary, stroke: .Text.secondary, shadow: .black,
        titleFill: .primary, titleStroke: .black, titleShadow: .black,
        danger: (.Semantic.Danger.text, .Semantic.Danger.accent),
        caution: (.Semantic.Caution.text, .Semantic.Caution.accent),
        success: (.Semantic.Success.text, .Semantic.Success.accent),
        info: (.Semantic.Info.text, .Semantic.Info.accent),
    )

    static let elyPink = SkinPalette(
        accent: .Skin.Elypink.Accent.text, accentMark: .Skin.Elypink.Accent.mark, onAccent: .Skin.Elypink.Accent.on,
        secondaryLabel: .Skin.Elypink.Text.secondary,
        background: .Skin.Elypink.Surface.background, cardBackground: .Skin.Elypink.Surface.card, inputBackground: .Skin.Elypink.Surface.input,
        eyebrow: .Skin.Elypink.eyebrow, stroke: .Skin.Elypink.stroke, shadow: .Skin.Elypink.shadow,
        titleFill: .Skin.Elypink.Title.fill, titleStroke: .Skin.Elypink.Title.stroke, titleShadow: .Skin.Elypink.Title.shadow,
        danger: (.Skin.Elypink.Semantic.Danger.text, .Skin.Elypink.Semantic.Danger.accent),
        caution: (.Skin.Elypink.Semantic.Caution.text, .Skin.Elypink.Semantic.Caution.accent),
        success: (.Skin.Elypink.Semantic.Success.text, .Skin.Elypink.Semantic.Success.accent),
        info: (.Skin.Elypink.Semantic.Info.text, .Skin.Elypink.Semantic.Info.accent),
    )

    static let tsuki = SkinPalette(
        accent: .Skin.Tsuki.Accent.text, accentMark: .Skin.Tsuki.Accent.mark, onAccent: .Skin.Tsuki.Accent.on,
        secondaryLabel: .Skin.Tsuki.Text.secondary,
        background: .Skin.Tsuki.Surface.background, cardBackground: .Skin.Tsuki.Surface.card, inputBackground: .Skin.Tsuki.Surface.input,
        eyebrow: .Skin.Tsuki.eyebrow, stroke: .Skin.Tsuki.stroke, shadow: .Skin.Tsuki.shadow,
        titleFill: .primary, titleStroke: .Skin.Tsuki.Title.stroke, titleShadow: .Skin.Tsuki.Title.shadow,
        danger: (.Skin.Tsuki.Semantic.Danger.text, .Skin.Tsuki.Semantic.Danger.accent),
        caution: (.Skin.Tsuki.Semantic.Caution.text, .Skin.Tsuki.Semantic.Caution.accent),
        success: (.Skin.Tsuki.Semantic.Success.text, .Skin.Tsuki.Semantic.Success.accent),
        info: (.Skin.Tsuki.Semantic.Info.text, .Skin.Tsuki.Semantic.Info.accent),
    )

    static let astrelia = SkinPalette(
        accent: .Skin.Astrelia.Accent.text, accentMark: .Skin.Astrelia.Accent.mark, onAccent: .Skin.Astrelia.Accent.on,
        secondaryLabel: .Skin.Astrelia.Text.secondary,
        background: .Skin.Astrelia.Surface.background, cardBackground: .Skin.Astrelia.Surface.card, inputBackground: .Skin.Astrelia.Surface.input,
        eyebrow: .Skin.Astrelia.eyebrow, stroke: .Skin.Astrelia.stroke, shadow: .Skin.Astrelia.shadow,
        titleFill: .Skin.Astrelia.Title.fill, titleStroke: .Skin.Astrelia.Title.stroke, titleShadow: .Skin.Astrelia.Title.shadow,
        danger: (.Skin.Astrelia.Semantic.Danger.text, .Skin.Astrelia.Semantic.Danger.accent),
        caution: (.Skin.Astrelia.Semantic.Caution.text, .Skin.Astrelia.Semantic.Caution.accent),
        success: (.Skin.Astrelia.Semantic.Success.text, .Skin.Astrelia.Semantic.Success.accent),
        info: (.Skin.Astrelia.Semantic.Info.text, .Skin.Astrelia.Semantic.Info.accent),
    )

    static let paperGarden = SkinPalette(
        accent: .Skin.Papergarden.Accent.text, accentMark: .Skin.Papergarden.Accent.mark, onAccent: .Skin.Papergarden.Accent.on,
        secondaryLabel: .Skin.Papergarden.Text.secondary,
        background: .Skin.Papergarden.Surface.background, cardBackground: .Skin.Papergarden.Surface.card, inputBackground: .Skin.Papergarden.Surface.input,
        eyebrow: .Skin.Papergarden.eyebrow, stroke: .Skin.Papergarden.stroke, shadow: .Skin.Papergarden.shadow,
        titleFill: .Skin.Papergarden.Title.fill, titleStroke: .Skin.Papergarden.Title.stroke, titleShadow: .Skin.Papergarden.Title.shadow,
        danger: (.Skin.Papergarden.Semantic.Danger.text, .Skin.Papergarden.Semantic.Danger.accent),
        caution: (.Skin.Papergarden.Semantic.Caution.text, .Skin.Papergarden.Semantic.Caution.accent),
        success: (.Skin.Papergarden.Semantic.Success.text, .Skin.Papergarden.Semantic.Success.accent),
        info: (.Skin.Papergarden.Semantic.Info.text, .Skin.Papergarden.Semantic.Info.accent),
    )

    static let hotaru = SkinPalette(
        accent: .Skin.Hotaru.Accent.text, accentMark: .Skin.Hotaru.Accent.mark, onAccent: .Skin.Hotaru.Accent.on,
        secondaryLabel: .Skin.Hotaru.Text.secondary,
        background: .Skin.Hotaru.Surface.background, cardBackground: .Skin.Hotaru.Surface.card, inputBackground: .Skin.Hotaru.Surface.input,
        eyebrow: .Skin.Hotaru.eyebrow, stroke: .Skin.Hotaru.stroke, shadow: .Skin.Hotaru.shadow,
        titleFill: .Skin.Hotaru.Title.fill, titleStroke: .Skin.Hotaru.Title.stroke, titleShadow: .Skin.Hotaru.Title.shadow,
        danger: (.Skin.Hotaru.Semantic.Danger.text, .Skin.Hotaru.Semantic.Danger.accent),
        caution: (.Skin.Hotaru.Semantic.Caution.text, .Skin.Hotaru.Semantic.Caution.accent),
        success: (.Skin.Hotaru.Semantic.Success.text, .Skin.Hotaru.Semantic.Success.accent),
        info: (.Skin.Hotaru.Semantic.Info.text, .Skin.Hotaru.Semantic.Info.accent),
    )

    static let yuki = SkinPalette(
        accent: .Skin.Yuki.Accent.text, accentMark: .Skin.Yuki.Accent.mark, onAccent: .Skin.Yuki.Accent.on,
        secondaryLabel: .Skin.Yuki.Text.secondary,
        background: .Skin.Yuki.Surface.background, cardBackground: .Skin.Yuki.Surface.card, inputBackground: .Skin.Yuki.Surface.input,
        eyebrow: .Skin.Yuki.eyebrow, stroke: .Skin.Yuki.stroke, shadow: .Skin.Yuki.shadow,
        titleFill: .Skin.Yuki.Title.fill, titleStroke: .Skin.Yuki.Title.stroke, titleShadow: .Skin.Yuki.Title.shadow,
        danger: (.Skin.Yuki.Semantic.Danger.text, .Skin.Yuki.Semantic.Danger.accent),
        caution: (.Skin.Yuki.Semantic.Caution.text, .Skin.Yuki.Semantic.Caution.accent),
        success: (.Skin.Yuki.Semantic.Success.text, .Skin.Yuki.Semantic.Success.accent),
        info: (.Skin.Yuki.Semantic.Info.text, .Skin.Yuki.Semantic.Info.accent),
    )

    static let hebi = SkinPalette(
        accent: .Skin.Hebi.Accent.text, accentMark: .Skin.Hebi.Accent.mark, onAccent: .Skin.Hebi.Accent.on,
        secondaryLabel: .Skin.Hebi.Text.secondary,
        background: .Skin.Hebi.Surface.background, cardBackground: .Skin.Hebi.Surface.card, inputBackground: .Skin.Hebi.Surface.input,
        eyebrow: .Skin.Hebi.eyebrow, stroke: .Skin.Hebi.stroke, shadow: .Skin.Hebi.shadow,
        titleFill: .Skin.Hebi.Title.fill, titleStroke: .Skin.Hebi.Title.stroke, titleShadow: .Skin.Hebi.Title.shadow,
        danger: (.Skin.Hebi.Semantic.Danger.text, .Skin.Hebi.Semantic.Danger.accent),
        caution: (.Skin.Hebi.Semantic.Caution.text, .Skin.Hebi.Semantic.Caution.accent),
        success: (.Skin.Hebi.Semantic.Success.text, .Skin.Hebi.Semantic.Success.accent),
        info: (.Skin.Hebi.Semantic.Info.text, .Skin.Hebi.Semantic.Info.accent),
    )

    static let kumo = SkinPalette(
        accent: .Skin.Kumo.Accent.text, accentMark: .Skin.Kumo.Accent.mark, onAccent: .Skin.Kumo.Accent.on,
        secondaryLabel: .Skin.Kumo.Text.secondary,
        background: .Skin.Kumo.Surface.background, cardBackground: .Skin.Kumo.Surface.card, inputBackground: .Skin.Kumo.Surface.input,
        eyebrow: .Skin.Kumo.eyebrow, stroke: .Skin.Kumo.stroke, shadow: .Skin.Kumo.shadow,
        titleFill: .Skin.Kumo.Title.fill, titleStroke: .Skin.Kumo.Title.stroke, titleShadow: .Skin.Kumo.Title.shadow,
        danger: (.Skin.Kumo.Semantic.Danger.text, .Skin.Kumo.Semantic.Danger.accent),
        caution: (.Skin.Kumo.Semantic.Caution.text, .Skin.Kumo.Semantic.Caution.accent),
        success: (.Skin.Kumo.Semantic.Success.text, .Skin.Kumo.Semantic.Success.accent),
        info: (.Skin.Kumo.Semantic.Info.text, .Skin.Kumo.Semantic.Info.accent),
    )

    static let doseWiki = SkinPalette(
        accent: .Skin.Dosewiki.Accent.text, accentMark: .Skin.Dosewiki.Accent.mark, onAccent: .Skin.Dosewiki.Accent.on,
        secondaryLabel: .Skin.Dosewiki.Text.secondary,
        background: .Skin.Dosewiki.Surface.background, cardBackground: .Skin.Dosewiki.Surface.card, inputBackground: .Skin.Dosewiki.Surface.input,
        eyebrow: .Skin.Dosewiki.eyebrow, stroke: .Skin.Dosewiki.stroke, shadow: .Skin.Dosewiki.shadow,
        titleFill: .Skin.Dosewiki.Title.fill, titleStroke: .Skin.Dosewiki.Title.stroke, titleShadow: .Skin.Dosewiki.Title.shadow,
        danger: (.Skin.Dosewiki.Semantic.Danger.text, .Skin.Dosewiki.Semantic.Danger.accent),
        caution: (.Skin.Dosewiki.Semantic.Caution.text, .Skin.Dosewiki.Semantic.Caution.accent),
        success: (.Skin.Dosewiki.Semantic.Success.text, .Skin.Dosewiki.Semantic.Success.accent),
        info: (.Skin.Dosewiki.Semantic.Info.text, .Skin.Dosewiki.Semantic.Info.accent),
    )

    static let jellyfish = SkinPalette(
        accent: .Skin.Jellyfish.Accent.text, accentMark: .Skin.Jellyfish.Accent.mark, onAccent: .Skin.Jellyfish.Accent.on,
        secondaryLabel: .Skin.Jellyfish.Text.secondary,
        background: .Skin.Jellyfish.Surface.background, cardBackground: .Skin.Jellyfish.Surface.card, inputBackground: .Skin.Jellyfish.Surface.input,
        eyebrow: .Skin.Jellyfish.eyebrow, stroke: .Skin.Jellyfish.stroke, shadow: .Skin.Jellyfish.shadow,
        titleFill: .primary, titleStroke: .Skin.Jellyfish.Title.stroke, titleShadow: .Skin.Jellyfish.Title.shadow,
        danger: (.Skin.Jellyfish.Semantic.Danger.text, .Skin.Jellyfish.Semantic.Danger.accent),
        caution: (.Skin.Jellyfish.Semantic.Caution.text, .Skin.Jellyfish.Semantic.Caution.accent),
        success: (.Skin.Jellyfish.Semantic.Success.text, .Skin.Jellyfish.Semantic.Success.accent),
        info: (.Skin.Jellyfish.Semantic.Info.text, .Skin.Jellyfish.Semantic.Info.accent),
    )
}

/// Font family names a skin bundles, by role. `nil` means the system face.
struct SkinTypeface: Equatable, Sendable {
    /// largeTitle · title · title2 · title3 · headline, and navigation titles.
    let display: String?
    /// Chips, badges — small categorical labels, never body copy or data.
    let label: String?
    /// Multiplies the display face's point size: a face set wide (a pixel
    /// face) needs less than the style's size to fit the same line.
    var displayScale: CGFloat = 1
}

/// The L1 status roles. A closed set — see `design-system/README.md`.
enum SemanticRole: CaseIterable, Sendable {
    case danger, caution, success, info
}

/// `text` is small copy (gated 4.5:1); `accent` is a standalone mark (3:1).
enum SemanticVariant: CaseIterable, Sendable {
    case text, accent
}

// MARK: - Decorations

/// A skin's decoration set: the scene `SkinBackdrop` draws behind every
/// screen, the glyph stickers it scatters over it, the pair that sits on a
/// glance card's corners, and the one that floats up from a tap.
struct SkinDecorations: Sendable {
    let scene: SkinScene
    /// Stickers scattered over the scene. Empty for none.
    let glyphs: [SkinGlyph]
    /// (top-right, bottom-left) on the large cards. `nil` for none.
    let frameCorners: (SkinGlyph, SkinGlyph)?
    /// Spawned at every tap by `TapTrail`. `nil` for none.
    let tapGlyph: SkinGlyph?
}

/// What `SkinBackdrop` paints under the stickers.
enum SkinScene: Sendable {
    /// ely.pink: a warm glow at the top and a faint dotted ground; the
    /// stickers carry the scene.
    case stickers
    /// A night sky: a twinkling, haloed starfield over nebula glows.
    case nightSky(SkinNightSky)
    /// Deep water: a depth gradient, light rays, rising bubbles, and
    /// jellyfish swimming up.
    case underwater(SkinUnderwater)
    /// Washi paper, raked sand around stones, sakura petals.
    case paper(SkinPaperGarden)
    /// A dark meadow: fireflies, fog, a tree line, an aurora.
    case fireflies(SkinFireflies)
    /// Falling snow and frost at the corners.
    case snow(SkinSnow)
    /// A perspective neon grid, pixel stars, a snake.
    case arcade(SkinArcade)
    /// A sky that follows the real time of day and season.
    case sky(SkinSky)
    /// dose.wiki: their page halos and their molecule ring, faint and slow.
    case molecule(SkinMolecule)
}

struct SkinMolecule: Sendable {
    /// The ring: their mark as a template image, resolved here on the main
    /// actor because the renderer is not.
    let image: ImageResource
    /// The ring is tinted with this.
    let ink: Color
    /// The site's page halos, top / left / right / bottom.
    let halos: [SkinGlow]
}

struct SkinPaperGarden: Sendable {
    let sand1: Color
    let sand2: Color
    let groove: Color
    let stone: Color
    let moss: Color
    let petal: Color
    let firefly: Color
    let grain: Color
}

struct SkinFireflies: Sendable {
    let core: Color
    let glow: Color
    let fog: Color
    let tree: Color
    /// Green, cyan, purple, pink — cycled along the ribbons.
    let aurora: [Color]
}

struct SkinSnow: Sendable {
    let flake: Color
    let frost: Color
}

struct SkinArcade: Sendable {
    let grid: Color
    let wall: Color
    let border: Color
    let snake: Color
    let snakeBody: Color
    let food: Color
    let star: Color
}

struct SkinSky: Sendable {
    let night: (Color, Color)
    let day: (Color, Color)
    let sunset: (Color, Color)
    let cloud: Color
    let star: Color
    let rain: Color
    let sun: Color
    let moon: Color
    let auroraPurple: Color
    let auroraCyan: Color
}

/// A radial glow on the ground: colour, centre, peak opacity.
nonisolated struct SkinGlow: Sendable {
    let color: Color
    let center: UnitPoint
    let opacity: Double

    init(_ color: Color, at center: UnitPoint, opacity: Double) {
        self.color = color
        self.center = center
        self.opacity = opacity
    }
}

struct SkinNightSky: Sendable {
    let starColor: Color
    let haloColor: Color
    /// 1.0 is Astrelia's dense field; Tsuki is sparser.
    let density: Double
    /// The star map's seed — two night skies must never share one.
    var seed: UInt64 = 0x57A2
    /// A denser diagonal band of faint stars, the Milky Way.
    var milkyWay = false
    /// A sleeping crescent moon.
    let moon: Bool
    /// The moon as drawn art — Tsuki's own icon, lifted with its glow — or
    /// `nil` to draw a crescent by hand.
    var moonImage: ImageResource? = nil
    /// The hand-drawn crescent's closed eyes and smile, and its blush.
    var moonInk: Color = .black
    var moonBlush: Color = .pink
    let glows: [SkinGlow]
}

struct SkinUnderwater: Sendable {
    /// The water column, bottom to top.
    let deep: Color
    let shallow: Color
    /// Light rays from the surface.
    let ray: Color
    let bubble: Color
    /// Bell colours the jellyfish cycle through.
    let bells: [Color]
}

/// One sticker glyph in a token colour.
struct SkinGlyph: Sendable {
    let symbol: String
    let color: Color

    init(_ symbol: String, _ color: Color) {
        self.symbol = symbol
        self.color = color
    }
}

/// A treated navigation title. Applied through UIKit's appearance proxy by
/// `SkinNavigationTitles` (large titles are drawn by the navigation bar, not
/// SwiftUI) and by `.skinHeroTitle()` on SwiftUI hero titles.
struct SkinTitleOutline: Sendable {
    /// `nil` keeps the label colour.
    let fill: Color?
    /// `nil` for no outline. Only the SwiftUI hero draws it — see
    /// `SkinNavigationTitles` for why the bar never strokes.
    let stroke: Color?
    let shadow: Color
    let shadowOffset: CGSize
    /// 0 for a hard drop; larger for a glow.
    let shadowBlur: CGFloat
}

/// The card treatment a skin asks for. See ``ThemedBackground``.
enum SkinSurface: Equatable, Sendable {
    /// `.ultraThinMaterial` in light, the skin's `cardBackground` in dark —
    /// the treatment the app shipped with.
    case glass
    /// Solid `cardBackground` in both schemes, a `strokeWidth` border in
    /// `stroke`, and a hard (unblurred) shadow of `shadow` offset by `shadowOffset`.
    case edged(stroke: Color, strokeWidth: CGFloat, shadow: Color, shadowOffset: CGSize)
    /// Solid `cardBackground`, a 1pt hairline in `stroke` at low opacity, and
    /// a coloured `glow` of `glowRadius` — never a black shadow.
    case soft(stroke: Color, glow: Color, glowRadius: CGFloat)
    /// Matte paper: solid fill, a 1pt ink `stroke` at low opacity, no shadow,
    /// and a `grain` tile over the fill.
    case paper(stroke: Color, grain: Color)
    /// Phosphor: a translucent dark fill, a 1.5pt `stroke` in the accent, an
    /// outer `glow` of the same colour, and an inner highlight line.
    case neon(stroke: Color, glow: Color)
    /// Frosted glass with no material: a translucent white fill, a white
    /// hairline `stroke`, and a `highlight` line along the top edge.
    case frosted(stroke: Color, highlight: Color)
}

/// The user's light/dark override. `system` defers to iOS.
enum SkinColorScheme: String, CaseIterable, Identifiable, Sendable {
    case system, light, dark

    var id: String { rawValue }

    /// Distinct from the dose-tier key `"Light"` (轻度), which is a different word.
    var displayName: LocalizedStringResource {
        switch self {
        case .system: "Follow System"
        case .light: "Light Mode"
        case .dark: "Dark Mode"
        }
    }

    /// What to hand `preferredColorScheme`. `nil` means follow the system.
    var colorScheme: ColorScheme? {
        switch self {
        case .system: nil
        case .light: .light
        case .dark: .dark
        }
    }
}

/// UserDefaults keys for the skin preference. One source of truth so the app's
/// `SkinStore` and the extensions read the same choice. Stored in the app group
/// suite so the widget and Live Activity can honour it.
nonisolated enum SkinDefaults {
    static let suite = "group.dev.yumeji.piru"
    static let skinKey = "skin"
    static let colorSchemeKey = "skinColorScheme"
    static let decorationsKey = "skinDecorations"
    static let skinDefault: Skin = .piru
    static let colorSchemeDefault: SkinColorScheme = .system
    static let decorationsDefault = true

    /// The persisted skin, for targets without a `SkinStore` (widgets). Falls
    /// back to the default when the stored value names a skin this build lacks.
    static func storedSkin(in defaults: UserDefaults? = UserDefaults(suiteName: suite)) -> Skin {
        guard let raw = defaults?.string(forKey: skinKey), let skin = Skin(rawValue: raw) else {
            return skinDefault
        }
        return skin
    }
}
