import SwiftUI

/// A skin is a named visual identity for the app: a palette, a surface
/// treatment, and a type design. It is *not* a light/dark pair — every skin
/// carries both appearances (and high-contrast variants) in the asset catalog,
/// so the system's colour scheme keeps working inside any skin.
///
/// ## Where a skin's colours live
///
/// In `Shared/Assets.xcassets`, under `skin/<id>/…`, generated by
/// `design-system/color/generate_colorsets.py` from `palette-generator-input.json`
/// exactly like the default tokens. Each accessor below switches on `self` and
/// returns the Xcode-generated symbol for that skin — never a string lookup, so
/// a missing colorset is a compile error, and `ColorContrastTests` gates every
/// skin against the same floors as the default.
///
/// The default skin reads the un-namespaced tokens (`surface/card`,
/// `text/secondary`, `AccentColor`) — the catalog the app shipped with, untouched.
///
/// ## What a skin never touches
///
/// Graphs. The timeline spine, sparklines and PK charts read `series.color`
/// and `Color.primary` with their own opacities and never see `Theme`, so a
/// skin cannot restyle them. Per-substance identity colours (L3) and the L2
/// encoding scales (routes, dose tiers, phases) are likewise not a skin's to
/// change — only their surrounding chrome is.
///
/// Lives in `Shared/` so the widget and Live Activity targets can resolve the
/// active skin's colours from the same catalog; the store that *chooses* the
/// skin (`SkinStore`) is app-only.
enum Skin: String, CaseIterable, Identifiable, Sendable {
    /// The app's own look: soft pink light, hot pink dark, Liquid Glass.
    case piru

    var id: String { rawValue }

    /// Picker name. Localized like every user-facing string.
    var displayName: LocalizedStringResource {
        switch self {
        case .piru: "Piru"
        }
    }

    /// One line under the name in the picker.
    var tagline: LocalizedStringResource {
        switch self {
        case .piru: "Soft pink, hot pink, liquid glass"
        }
    }

    // MARK: - Palette

    /// Brand accent and control tint.
    var accent: Color {
        switch self {
        case .piru: .accent
        }
    }

    /// De-emphasized body text. Gated AA 4.5:1 on `cardBackground`.
    var secondaryLabel: Color {
        switch self {
        case .piru: .Text.secondary
        }
    }

    /// Page backdrop.
    var background: Color {
        switch self {
        case .piru: .Surface.background
        }
    }

    /// Card / raised surface fill.
    var cardBackground: Color {
        switch self {
        case .piru: .Surface.card
        }
    }

    /// Text-field and other input fills.
    var inputBackground: Color {
        switch self {
        case .piru: .Surface.input
        }
    }

    // MARK: - Surface treatment

    /// How cards and capsules are drawn. The default skin keeps the app's
    /// scheme-adaptive material; an edged skin draws a solid fill with a stroke
    /// and a hard offset shadow instead of any material.
    var surface: SkinSurface {
        switch self {
        case .piru: .glass
        }
    }

    // MARK: - Type

    /// Applied once at the root. `nil` keeps the system default design; this
    /// reshapes every semantic text style in the app without touching call
    /// sites. Custom families are the typography layer's job, not this one's.
    var fontDesign: Font.Design? {
        switch self {
        case .piru: nil
        }
    }
}

/// The card treatment a skin asks for. See ``ThemedBackground``.
enum SkinSurface: Equatable, Sendable {
    /// `.ultraThinMaterial` in light, the skin's `cardBackground` in dark —
    /// the treatment the app shipped with.
    case glass
    /// Solid `cardBackground` in both schemes, a `strokeWidth` border in
    /// `stroke`, and a hard (unblurred) shadow of `shadow` offset by `shadowOffset`.
    case edged(stroke: Color, strokeWidth: CGFloat, shadow: Color, shadowOffset: CGSize)
}

/// The user's light/dark override. `system` defers to iOS.
enum SkinColorScheme: String, CaseIterable, Identifiable, Sendable {
    case system, light, dark

    var id: String { rawValue }

    /// Distinct from the dose-tier key `"Light"` (轻度), which is a different word.
    var displayName: LocalizedStringResource {
        switch self {
        case .system: "Follow System"
        case .light: "Light Mode"
        case .dark: "Dark Mode"
        }
    }

    /// What to hand `preferredColorScheme`. `nil` means follow the system.
    var colorScheme: ColorScheme? {
        switch self {
        case .system: nil
        case .light: .light
        case .dark: .dark
        }
    }
}

/// UserDefaults keys for the skin preference. One source of truth so the app's
/// `SkinStore` and the extensions read the same choice. Stored in the app group
/// suite so the widget and Live Activity can honour it.
enum SkinDefaults {
    static let suite = "group.dev.yumeji.piru"
    static let skinKey = "skin"
    static let colorSchemeKey = "skinColorScheme"
    static let skinDefault: Skin = .piru
    static let colorSchemeDefault: SkinColorScheme = .system

    /// The persisted skin, for targets without a `SkinStore` (widgets). Falls
    /// back to the default when the stored value names a skin this build lacks.
    static func storedSkin(in defaults: UserDefaults? = UserDefaults(suiteName: suite)) -> Skin {
        guard let raw = defaults?.string(forKey: skinKey), let skin = Skin(rawValue: raw) else {
            return skinDefault
        }
        return skin
    }
}
