// GENERATED by generate_colorsets.py -- do not hand-edit.
// Regenerate: python3 Specs/design-system/color-audit/generate_colorsets.py <palette.json> --out ... --swift-out ...
import SwiftUI

/// Typed accessors for the generated color-catalog tokens. Each is
/// `nonisolated` -- an asset-catalog `Color(_:)` lookup holds no
/// actor-isolated state (verified: compiles under `-default-isolation
/// MainActor -strict-concurrency=complete` as `nonisolated`), so callers
/// off the main actor don't need to hop to read one.
enum GeneratedTheme {
    /// Catalog color `"semantic/caution/accent"`.
    nonisolated static let semanticCautionAccent = Color("semantic/caution/accent", bundle: .main)
    /// Catalog color `"semantic/caution/text"`.
    nonisolated static let semanticCautionText = Color("semantic/caution/text", bundle: .main)
    /// Catalog color `"semantic/danger/accent"`.
    nonisolated static let semanticDangerAccent = Color("semantic/danger/accent", bundle: .main)
    /// Catalog color `"semantic/danger/text"`.
    nonisolated static let semanticDangerText = Color("semantic/danger/text", bundle: .main)
    /// Catalog color `"semantic/info/accent"`.
    nonisolated static let semanticInfoAccent = Color("semantic/info/accent", bundle: .main)
    /// Catalog color `"semantic/info/text"`.
    nonisolated static let semanticInfoText = Color("semantic/info/text", bundle: .main)
    /// Catalog color `"semantic/success/accent"`.
    nonisolated static let semanticSuccessAccent = Color("semantic/success/accent", bundle: .main)
    /// Catalog color `"semantic/success/text"`.
    nonisolated static let semanticSuccessText = Color("semantic/success/text", bundle: .main)
}
